<?php


/**
 * This class adds structure of 'j019t_participantes' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Wed Nov 11 13:50:04 2015
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class J019tParticipantesMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.J019tParticipantesMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(J019tParticipantesPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(J019tParticipantesPeer::TABLE_NAME);
		$tMap->setPhpName('J019tParticipantes');
		$tMap->setClassname('J019tParticipantes');

		$tMap->setUseIdGenerator(false);

		$tMap->addPrimaryKey('CO_PARTICIPANTE', 'CoParticipante', 'BIGINT', true, null);

		$tMap->addForeignKey('CO_USUARIO_ELABORA', 'CoUsuarioElabora', 'BIGINT', 'j002t_usuario', 'CO_USUARIO', false, null);

		$tMap->addForeignKey('CO_FORENSE', 'CoForense', 'BIGINT', 'j016t_forense', 'CO_FORENSE', false, null);

		$tMap->addColumn('CO_INFORME_RECOMENDACIONES', 'CoInformeRecomendaciones', 'BIGINT', false, null);

		$tMap->addColumn('CO_INFORME_INCIDENTE', 'CoInformeIncidente', 'BIGINT', false, null);

		$tMap->addForeignKey('CO_INFORME_FORENSE', 'CoInformeForense', 'BIGINT', 'j018t_informe_forense', 'CO_INFORME_FORENSE', false, null);

		$tMap->addColumn('CO_INFORME_DEPURACION', 'CoInformeDepuracion', 'BIGINT', false, null);

		$tMap->addColumn('CO_MANTENIMIENTO', 'CoMantenimiento', 'BIGINT', false, null);

		$tMap->addColumn('CO_DOUMENTO_NORMATIVO', 'CoDoumentoNormativo', 'BIGINT', false, null);

	} // doBuild()

} // J019tParticipantesMapBuilder
