<?php


/**
 * This class adds structure of 'j023t_evidencia' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu Nov 12 11:16:19 2015
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class J023tEvidenciaMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.J023tEvidenciaMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(J023tEvidenciaPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(J023tEvidenciaPeer::TABLE_NAME);
		$tMap->setPhpName('J023tEvidencia');
		$tMap->setClassname('J023tEvidencia');

		$tMap->setUseIdGenerator(false);

		$tMap->addPrimaryKey('CO_EVIDENCIA', 'CoEvidencia', 'BIGINT', true, null);

		$tMap->addColumn('FE_REGISTRO', 'FeRegistro', 'DATE', false, null);

		$tMap->addForeignKey('CO_REGISTRO', 'CoRegistro', 'BIGINT', 'j002t_usuario', 'CO_USUARIO', false, null);

		$tMap->addForeignKey('CO_ACC', 'CoAcc', 'BIGINT', 'j020t_acta_acc', 'CO_ACC', false, null);

		$tMap->addForeignKey('CO_AIE', 'CoAie', 'BIGINT', 'j021t_acta_aie', 'CO_AIE', false, null);

		$tMap->addColumn('TX_DESCRIPCION_COLECCION', 'TxDescripcionColeccion', 'LONGVARCHAR', false, null);

		$tMap->addColumn('FE_COLECCION_EVIDENCIA', 'FeColeccionEvidencia', 'DATE', false, null);

		$tMap->addForeignKey('CO_COLECTA', 'CoColecta', 'BIGINT', 'j002t_usuario', 'CO_USUARIO', false, null);

		$tMap->addColumn('CO_RECURSO', 'CoRecurso', 'BIGINT', false, null);

		$tMap->addColumn('TX_NOMBRE_RECURSO', 'TxNombreRecurso', 'BIGINT', false, null);

		$tMap->addColumn('TX_SERIAL_RECURSO', 'TxSerialRecurso', 'BIGINT', false, null);

		$tMap->addColumn('TX_MARCA_RECURSO', 'TxMarcaRecurso', 'LONGVARCHAR', false, null);

		$tMap->addColumn('TX_MODELO_RECURSO', 'TxModeloRecurso', 'BIGINT', false, null);

		$tMap->addColumn('TX_NUMERO_ACTIVO', 'TxNumeroActivo', 'BIGINT', false, null);

		$tMap->addForeignKey('CO_TIPO_EVIDENCIA', 'CoTipoEvidencia', 'BIGINT', 'j025t_tipo_evidencia', 'CO_TIPO_EVIDENCIA', false, null);

		$tMap->addForeignKey('CO_ESTADO_EVIDENCIA', 'CoEstadoEvidencia', 'BIGINT', 'j026t_estado_evidencia', 'CO_ESTADO_EVIDENCIA', false, null);

		$tMap->addForeignKey('CO_LUGAR_SEGURO', 'CoLugarSeguro', 'BIGINT', 'j027t_lugar_seguro', 'CO_LUGAR_SEGURO', false, null);

		$tMap->addForeignKey('CO_REPOSITORIO', 'CoRepositorio', 'BIGINT', 'j028t_repositorio', 'CO_REPOSITORIO', false, null);

		$tMap->addForeignKey('CO_CUSTODIO_STI', 'CoCustodioSti', 'BIGINT', 'j002t_usuario', 'CO_USUARIO', false, null);

		$tMap->addColumn('TX_OBSERVACIONES', 'TxObservaciones', 'LONGVARCHAR', false, null);

		$tMap->addColumn('UPDATE_AT', 'UpdateAt', 'TIMESTAMP', false, null);

		$tMap->addForeignKey('CO_UPDATE_AT', 'CoUpdateAt', 'BIGINT', 'j002t_usuario', 'CO_USUARIO', false, null);

	} // doBuild()

} // J023tEvidenciaMapBuilder
