<?php

/**
 * Base class that represents a row from the 'j045t_referencia_marco' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Nov  9 14:57:52 2015
 *
 * @package    lib.model.om
 */
abstract class BaseJ045tReferenciaMarco extends BaseObject  implements Persistent {


  const PEER = 'J045tReferenciaMarcoPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        J045tReferenciaMarcoPeer
	 */
	protected static $peer;

	/**
	 * The value for the co_referencia_marco field.
	 * @var        string
	 */
	protected $co_referencia_marco;

	/**
	 * The value for the co_marco_normativo field.
	 * @var        string
	 */
	protected $co_marco_normativo;

	/**
	 * The value for the co_incidente field.
	 * @var        string
	 */
	protected $co_incidente;

	/**
	 * The value for the co_recomendaciones field.
	 * @var        string
	 */
	protected $co_recomendaciones;

	/**
	 * The value for the co_monitoreo field.
	 * @var        string
	 */
	protected $co_monitoreo;

	/**
	 * The value for the co_forense field.
	 * @var        string
	 */
	protected $co_forense;

	/**
	 * The value for the co_depuracion field.
	 * @var        string
	 */
	protected $co_depuracion;

	/**
	 * The value for the co_cumple field.
	 * @var        boolean
	 */
	protected $co_cumple;

	/**
	 * The value for the co_accion field.
	 * @var        string
	 */
	protected $co_accion;

	/**
	 * @var        J046tMarcoNormativo
	 */
	protected $aJ046tMarcoNormativo;

	/**
	 * @var        J034tIncidente
	 */
	protected $aJ034tIncidente;

	/**
	 * @var        J030tInformeRecomendaciones
	 */
	protected $aJ030tInformeRecomendaciones;

	/**
	 * @var        J016tForense
	 */
	protected $aJ016tForense;

	/**
	 * @var        J031tAccionRecomendada
	 */
	protected $aJ031tAccionRecomendada;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseJ045tReferenciaMarco object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [co_referencia_marco] column value.
	 * 
	 * @return     string
	 */
	public function getCoReferenciaMarco()
	{
		return $this->co_referencia_marco;
	}

	/**
	 * Get the [co_marco_normativo] column value.
	 * 
	 * @return     string
	 */
	public function getCoMarcoNormativo()
	{
		return $this->co_marco_normativo;
	}

	/**
	 * Get the [co_incidente] column value.
	 * 
	 * @return     string
	 */
	public function getCoIncidente()
	{
		return $this->co_incidente;
	}

	/**
	 * Get the [co_recomendaciones] column value.
	 * 
	 * @return     string
	 */
	public function getCoRecomendaciones()
	{
		return $this->co_recomendaciones;
	}

	/**
	 * Get the [co_monitoreo] column value.
	 * 
	 * @return     string
	 */
	public function getCoMonitoreo()
	{
		return $this->co_monitoreo;
	}

	/**
	 * Get the [co_forense] column value.
	 * 
	 * @return     string
	 */
	public function getCoForense()
	{
		return $this->co_forense;
	}

	/**
	 * Get the [co_depuracion] column value.
	 * 
	 * @return     string
	 */
	public function getCoDepuracion()
	{
		return $this->co_depuracion;
	}

	/**
	 * Get the [co_cumple] column value.
	 * 
	 * @return     boolean
	 */
	public function getCoCumple()
	{
		return $this->co_cumple;
	}

	/**
	 * Get the [co_accion] column value.
	 * 
	 * @return     string
	 */
	public function getCoAccion()
	{
		return $this->co_accion;
	}

	/**
	 * Set the value of [co_referencia_marco] column.
	 * 
	 * @param      string $v new value
	 * @return     J045tReferenciaMarco The current object (for fluent API support)
	 */
	public function setCoReferenciaMarco($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_referencia_marco !== $v) {
			$this->co_referencia_marco = $v;
			$this->modifiedColumns[] = J045tReferenciaMarcoPeer::CO_REFERENCIA_MARCO;
		}

		return $this;
	} // setCoReferenciaMarco()

	/**
	 * Set the value of [co_marco_normativo] column.
	 * 
	 * @param      string $v new value
	 * @return     J045tReferenciaMarco The current object (for fluent API support)
	 */
	public function setCoMarcoNormativo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_marco_normativo !== $v) {
			$this->co_marco_normativo = $v;
			$this->modifiedColumns[] = J045tReferenciaMarcoPeer::CO_MARCO_NORMATIVO;
		}

		if ($this->aJ046tMarcoNormativo !== null && $this->aJ046tMarcoNormativo->getCoMarcoNormativo() !== $v) {
			$this->aJ046tMarcoNormativo = null;
		}

		return $this;
	} // setCoMarcoNormativo()

	/**
	 * Set the value of [co_incidente] column.
	 * 
	 * @param      string $v new value
	 * @return     J045tReferenciaMarco The current object (for fluent API support)
	 */
	public function setCoIncidente($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_incidente !== $v) {
			$this->co_incidente = $v;
			$this->modifiedColumns[] = J045tReferenciaMarcoPeer::CO_INCIDENTE;
		}

		if ($this->aJ034tIncidente !== null && $this->aJ034tIncidente->getCoIncidente() !== $v) {
			$this->aJ034tIncidente = null;
		}

		return $this;
	} // setCoIncidente()

	/**
	 * Set the value of [co_recomendaciones] column.
	 * 
	 * @param      string $v new value
	 * @return     J045tReferenciaMarco The current object (for fluent API support)
	 */
	public function setCoRecomendaciones($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_recomendaciones !== $v) {
			$this->co_recomendaciones = $v;
			$this->modifiedColumns[] = J045tReferenciaMarcoPeer::CO_RECOMENDACIONES;
		}

		if ($this->aJ030tInformeRecomendaciones !== null && $this->aJ030tInformeRecomendaciones->getCoInformeRecomendaciones() !== $v) {
			$this->aJ030tInformeRecomendaciones = null;
		}

		return $this;
	} // setCoRecomendaciones()

	/**
	 * Set the value of [co_monitoreo] column.
	 * 
	 * @param      string $v new value
	 * @return     J045tReferenciaMarco The current object (for fluent API support)
	 */
	public function setCoMonitoreo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_monitoreo !== $v) {
			$this->co_monitoreo = $v;
			$this->modifiedColumns[] = J045tReferenciaMarcoPeer::CO_MONITOREO;
		}

		return $this;
	} // setCoMonitoreo()

	/**
	 * Set the value of [co_forense] column.
	 * 
	 * @param      string $v new value
	 * @return     J045tReferenciaMarco The current object (for fluent API support)
	 */
	public function setCoForense($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_forense !== $v) {
			$this->co_forense = $v;
			$this->modifiedColumns[] = J045tReferenciaMarcoPeer::CO_FORENSE;
		}

		if ($this->aJ016tForense !== null && $this->aJ016tForense->getCoForense() !== $v) {
			$this->aJ016tForense = null;
		}

		return $this;
	} // setCoForense()

	/**
	 * Set the value of [co_depuracion] column.
	 * 
	 * @param      string $v new value
	 * @return     J045tReferenciaMarco The current object (for fluent API support)
	 */
	public function setCoDepuracion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_depuracion !== $v) {
			$this->co_depuracion = $v;
			$this->modifiedColumns[] = J045tReferenciaMarcoPeer::CO_DEPURACION;
		}

		return $this;
	} // setCoDepuracion()

	/**
	 * Set the value of [co_cumple] column.
	 * 
	 * @param      boolean $v new value
	 * @return     J045tReferenciaMarco The current object (for fluent API support)
	 */
	public function setCoCumple($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->co_cumple !== $v) {
			$this->co_cumple = $v;
			$this->modifiedColumns[] = J045tReferenciaMarcoPeer::CO_CUMPLE;
		}

		return $this;
	} // setCoCumple()

	/**
	 * Set the value of [co_accion] column.
	 * 
	 * @param      string $v new value
	 * @return     J045tReferenciaMarco The current object (for fluent API support)
	 */
	public function setCoAccion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_accion !== $v) {
			$this->co_accion = $v;
			$this->modifiedColumns[] = J045tReferenciaMarcoPeer::CO_ACCION;
		}

		if ($this->aJ031tAccionRecomendada !== null && $this->aJ031tAccionRecomendada->getCoAccion() !== $v) {
			$this->aJ031tAccionRecomendada = null;
		}

		return $this;
	} // setCoAccion()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->co_referencia_marco = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
			$this->co_marco_normativo = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->co_incidente = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->co_recomendaciones = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->co_monitoreo = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->co_forense = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->co_depuracion = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->co_cumple = ($row[$startcol + 7] !== null) ? (boolean) $row[$startcol + 7] : null;
			$this->co_accion = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 9; // 9 = J045tReferenciaMarcoPeer::NUM_COLUMNS - J045tReferenciaMarcoPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating J045tReferenciaMarco object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aJ046tMarcoNormativo !== null && $this->co_marco_normativo !== $this->aJ046tMarcoNormativo->getCoMarcoNormativo()) {
			$this->aJ046tMarcoNormativo = null;
		}
		if ($this->aJ034tIncidente !== null && $this->co_incidente !== $this->aJ034tIncidente->getCoIncidente()) {
			$this->aJ034tIncidente = null;
		}
		if ($this->aJ030tInformeRecomendaciones !== null && $this->co_recomendaciones !== $this->aJ030tInformeRecomendaciones->getCoInformeRecomendaciones()) {
			$this->aJ030tInformeRecomendaciones = null;
		}
		if ($this->aJ016tForense !== null && $this->co_forense !== $this->aJ016tForense->getCoForense()) {
			$this->aJ016tForense = null;
		}
		if ($this->aJ031tAccionRecomendada !== null && $this->co_accion !== $this->aJ031tAccionRecomendada->getCoAccion()) {
			$this->aJ031tAccionRecomendada = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(J045tReferenciaMarcoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = J045tReferenciaMarcoPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aJ046tMarcoNormativo = null;
			$this->aJ034tIncidente = null;
			$this->aJ030tInformeRecomendaciones = null;
			$this->aJ016tForense = null;
			$this->aJ031tAccionRecomendada = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseJ045tReferenciaMarco:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(J045tReferenciaMarcoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			J045tReferenciaMarcoPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseJ045tReferenciaMarco:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseJ045tReferenciaMarco:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(J045tReferenciaMarcoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseJ045tReferenciaMarco:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			J045tReferenciaMarcoPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aJ046tMarcoNormativo !== null) {
				if ($this->aJ046tMarcoNormativo->isModified() || $this->aJ046tMarcoNormativo->isNew()) {
					$affectedRows += $this->aJ046tMarcoNormativo->save($con);
				}
				$this->setJ046tMarcoNormativo($this->aJ046tMarcoNormativo);
			}

			if ($this->aJ034tIncidente !== null) {
				if ($this->aJ034tIncidente->isModified() || $this->aJ034tIncidente->isNew()) {
					$affectedRows += $this->aJ034tIncidente->save($con);
				}
				$this->setJ034tIncidente($this->aJ034tIncidente);
			}

			if ($this->aJ030tInformeRecomendaciones !== null) {
				if ($this->aJ030tInformeRecomendaciones->isModified() || $this->aJ030tInformeRecomendaciones->isNew()) {
					$affectedRows += $this->aJ030tInformeRecomendaciones->save($con);
				}
				$this->setJ030tInformeRecomendaciones($this->aJ030tInformeRecomendaciones);
			}

			if ($this->aJ016tForense !== null) {
				if ($this->aJ016tForense->isModified() || $this->aJ016tForense->isNew()) {
					$affectedRows += $this->aJ016tForense->save($con);
				}
				$this->setJ016tForense($this->aJ016tForense);
			}

			if ($this->aJ031tAccionRecomendada !== null) {
				if ($this->aJ031tAccionRecomendada->isModified() || $this->aJ031tAccionRecomendada->isNew()) {
					$affectedRows += $this->aJ031tAccionRecomendada->save($con);
				}
				$this->setJ031tAccionRecomendada($this->aJ031tAccionRecomendada);
			}


			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = J045tReferenciaMarcoPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setNew(false);
				} else {
					$affectedRows += J045tReferenciaMarcoPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aJ046tMarcoNormativo !== null) {
				if (!$this->aJ046tMarcoNormativo->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aJ046tMarcoNormativo->getValidationFailures());
				}
			}

			if ($this->aJ034tIncidente !== null) {
				if (!$this->aJ034tIncidente->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aJ034tIncidente->getValidationFailures());
				}
			}

			if ($this->aJ030tInformeRecomendaciones !== null) {
				if (!$this->aJ030tInformeRecomendaciones->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aJ030tInformeRecomendaciones->getValidationFailures());
				}
			}

			if ($this->aJ016tForense !== null) {
				if (!$this->aJ016tForense->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aJ016tForense->getValidationFailures());
				}
			}

			if ($this->aJ031tAccionRecomendada !== null) {
				if (!$this->aJ031tAccionRecomendada->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aJ031tAccionRecomendada->getValidationFailures());
				}
			}


			if (($retval = J045tReferenciaMarcoPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = J045tReferenciaMarcoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getCoReferenciaMarco();
				break;
			case 1:
				return $this->getCoMarcoNormativo();
				break;
			case 2:
				return $this->getCoIncidente();
				break;
			case 3:
				return $this->getCoRecomendaciones();
				break;
			case 4:
				return $this->getCoMonitoreo();
				break;
			case 5:
				return $this->getCoForense();
				break;
			case 6:
				return $this->getCoDepuracion();
				break;
			case 7:
				return $this->getCoCumple();
				break;
			case 8:
				return $this->getCoAccion();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = J045tReferenciaMarcoPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getCoReferenciaMarco(),
			$keys[1] => $this->getCoMarcoNormativo(),
			$keys[2] => $this->getCoIncidente(),
			$keys[3] => $this->getCoRecomendaciones(),
			$keys[4] => $this->getCoMonitoreo(),
			$keys[5] => $this->getCoForense(),
			$keys[6] => $this->getCoDepuracion(),
			$keys[7] => $this->getCoCumple(),
			$keys[8] => $this->getCoAccion(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = J045tReferenciaMarcoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setCoReferenciaMarco($value);
				break;
			case 1:
				$this->setCoMarcoNormativo($value);
				break;
			case 2:
				$this->setCoIncidente($value);
				break;
			case 3:
				$this->setCoRecomendaciones($value);
				break;
			case 4:
				$this->setCoMonitoreo($value);
				break;
			case 5:
				$this->setCoForense($value);
				break;
			case 6:
				$this->setCoDepuracion($value);
				break;
			case 7:
				$this->setCoCumple($value);
				break;
			case 8:
				$this->setCoAccion($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = J045tReferenciaMarcoPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setCoReferenciaMarco($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setCoMarcoNormativo($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setCoIncidente($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setCoRecomendaciones($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setCoMonitoreo($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setCoForense($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setCoDepuracion($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setCoCumple($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setCoAccion($arr[$keys[8]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(J045tReferenciaMarcoPeer::DATABASE_NAME);

		if ($this->isColumnModified(J045tReferenciaMarcoPeer::CO_REFERENCIA_MARCO)) $criteria->add(J045tReferenciaMarcoPeer::CO_REFERENCIA_MARCO, $this->co_referencia_marco);
		if ($this->isColumnModified(J045tReferenciaMarcoPeer::CO_MARCO_NORMATIVO)) $criteria->add(J045tReferenciaMarcoPeer::CO_MARCO_NORMATIVO, $this->co_marco_normativo);
		if ($this->isColumnModified(J045tReferenciaMarcoPeer::CO_INCIDENTE)) $criteria->add(J045tReferenciaMarcoPeer::CO_INCIDENTE, $this->co_incidente);
		if ($this->isColumnModified(J045tReferenciaMarcoPeer::CO_RECOMENDACIONES)) $criteria->add(J045tReferenciaMarcoPeer::CO_RECOMENDACIONES, $this->co_recomendaciones);
		if ($this->isColumnModified(J045tReferenciaMarcoPeer::CO_MONITOREO)) $criteria->add(J045tReferenciaMarcoPeer::CO_MONITOREO, $this->co_monitoreo);
		if ($this->isColumnModified(J045tReferenciaMarcoPeer::CO_FORENSE)) $criteria->add(J045tReferenciaMarcoPeer::CO_FORENSE, $this->co_forense);
		if ($this->isColumnModified(J045tReferenciaMarcoPeer::CO_DEPURACION)) $criteria->add(J045tReferenciaMarcoPeer::CO_DEPURACION, $this->co_depuracion);
		if ($this->isColumnModified(J045tReferenciaMarcoPeer::CO_CUMPLE)) $criteria->add(J045tReferenciaMarcoPeer::CO_CUMPLE, $this->co_cumple);
		if ($this->isColumnModified(J045tReferenciaMarcoPeer::CO_ACCION)) $criteria->add(J045tReferenciaMarcoPeer::CO_ACCION, $this->co_accion);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(J045tReferenciaMarcoPeer::DATABASE_NAME);

		$criteria->add(J045tReferenciaMarcoPeer::CO_REFERENCIA_MARCO, $this->co_referencia_marco);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     string
	 */
	public function getPrimaryKey()
	{
		return $this->getCoReferenciaMarco();
	}

	/**
	 * Generic method to set the primary key (co_referencia_marco column).
	 *
	 * @param      string $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setCoReferenciaMarco($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of J045tReferenciaMarco (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setCoReferenciaMarco($this->co_referencia_marco);

		$copyObj->setCoMarcoNormativo($this->co_marco_normativo);

		$copyObj->setCoIncidente($this->co_incidente);

		$copyObj->setCoRecomendaciones($this->co_recomendaciones);

		$copyObj->setCoMonitoreo($this->co_monitoreo);

		$copyObj->setCoForense($this->co_forense);

		$copyObj->setCoDepuracion($this->co_depuracion);

		$copyObj->setCoCumple($this->co_cumple);

		$copyObj->setCoAccion($this->co_accion);


		$copyObj->setNew(true);

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     J045tReferenciaMarco Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     J045tReferenciaMarcoPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new J045tReferenciaMarcoPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a J046tMarcoNormativo object.
	 *
	 * @param      J046tMarcoNormativo $v
	 * @return     J045tReferenciaMarco The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setJ046tMarcoNormativo(J046tMarcoNormativo $v = null)
	{
		if ($v === null) {
			$this->setCoMarcoNormativo(NULL);
		} else {
			$this->setCoMarcoNormativo($v->getCoMarcoNormativo());
		}

		$this->aJ046tMarcoNormativo = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the J046tMarcoNormativo object, it will not be re-added.
		if ($v !== null) {
			$v->addJ045tReferenciaMarco($this);
		}

		return $this;
	}


	/**
	 * Get the associated J046tMarcoNormativo object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     J046tMarcoNormativo The associated J046tMarcoNormativo object.
	 * @throws     PropelException
	 */
	public function getJ046tMarcoNormativo(PropelPDO $con = null)
	{
		if ($this->aJ046tMarcoNormativo === null && (($this->co_marco_normativo !== "" && $this->co_marco_normativo !== null))) {
			$c = new Criteria(J046tMarcoNormativoPeer::DATABASE_NAME);
			$c->add(J046tMarcoNormativoPeer::CO_MARCO_NORMATIVO, $this->co_marco_normativo);
			$this->aJ046tMarcoNormativo = J046tMarcoNormativoPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aJ046tMarcoNormativo->addJ045tReferenciaMarcos($this);
			 */
		}
		return $this->aJ046tMarcoNormativo;
	}

	/**
	 * Declares an association between this object and a J034tIncidente object.
	 *
	 * @param      J034tIncidente $v
	 * @return     J045tReferenciaMarco The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setJ034tIncidente(J034tIncidente $v = null)
	{
		if ($v === null) {
			$this->setCoIncidente(NULL);
		} else {
			$this->setCoIncidente($v->getCoIncidente());
		}

		$this->aJ034tIncidente = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the J034tIncidente object, it will not be re-added.
		if ($v !== null) {
			$v->addJ045tReferenciaMarco($this);
		}

		return $this;
	}


	/**
	 * Get the associated J034tIncidente object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     J034tIncidente The associated J034tIncidente object.
	 * @throws     PropelException
	 */
	public function getJ034tIncidente(PropelPDO $con = null)
	{
		if ($this->aJ034tIncidente === null && (($this->co_incidente !== "" && $this->co_incidente !== null))) {
			$c = new Criteria(J034tIncidentePeer::DATABASE_NAME);
			$c->add(J034tIncidentePeer::CO_INCIDENTE, $this->co_incidente);
			$this->aJ034tIncidente = J034tIncidentePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aJ034tIncidente->addJ045tReferenciaMarcos($this);
			 */
		}
		return $this->aJ034tIncidente;
	}

	/**
	 * Declares an association between this object and a J030tInformeRecomendaciones object.
	 *
	 * @param      J030tInformeRecomendaciones $v
	 * @return     J045tReferenciaMarco The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setJ030tInformeRecomendaciones(J030tInformeRecomendaciones $v = null)
	{
		if ($v === null) {
			$this->setCoRecomendaciones(NULL);
		} else {
			$this->setCoRecomendaciones($v->getCoInformeRecomendaciones());
		}

		$this->aJ030tInformeRecomendaciones = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the J030tInformeRecomendaciones object, it will not be re-added.
		if ($v !== null) {
			$v->addJ045tReferenciaMarco($this);
		}

		return $this;
	}


	/**
	 * Get the associated J030tInformeRecomendaciones object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     J030tInformeRecomendaciones The associated J030tInformeRecomendaciones object.
	 * @throws     PropelException
	 */
	public function getJ030tInformeRecomendaciones(PropelPDO $con = null)
	{
		if ($this->aJ030tInformeRecomendaciones === null && (($this->co_recomendaciones !== "" && $this->co_recomendaciones !== null))) {
			$c = new Criteria(J030tInformeRecomendacionesPeer::DATABASE_NAME);
			$c->add(J030tInformeRecomendacionesPeer::CO_INFORME_RECOMENDACIONES, $this->co_recomendaciones);
			$this->aJ030tInformeRecomendaciones = J030tInformeRecomendacionesPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aJ030tInformeRecomendaciones->addJ045tReferenciaMarcos($this);
			 */
		}
		return $this->aJ030tInformeRecomendaciones;
	}

	/**
	 * Declares an association between this object and a J016tForense object.
	 *
	 * @param      J016tForense $v
	 * @return     J045tReferenciaMarco The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setJ016tForense(J016tForense $v = null)
	{
		if ($v === null) {
			$this->setCoForense(NULL);
		} else {
			$this->setCoForense($v->getCoForense());
		}

		$this->aJ016tForense = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the J016tForense object, it will not be re-added.
		if ($v !== null) {
			$v->addJ045tReferenciaMarco($this);
		}

		return $this;
	}


	/**
	 * Get the associated J016tForense object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     J016tForense The associated J016tForense object.
	 * @throws     PropelException
	 */
	public function getJ016tForense(PropelPDO $con = null)
	{
		if ($this->aJ016tForense === null && (($this->co_forense !== "" && $this->co_forense !== null))) {
			$c = new Criteria(J016tForensePeer::DATABASE_NAME);
			$c->add(J016tForensePeer::CO_FORENSE, $this->co_forense);
			$this->aJ016tForense = J016tForensePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aJ016tForense->addJ045tReferenciaMarcos($this);
			 */
		}
		return $this->aJ016tForense;
	}

	/**
	 * Declares an association between this object and a J031tAccionRecomendada object.
	 *
	 * @param      J031tAccionRecomendada $v
	 * @return     J045tReferenciaMarco The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setJ031tAccionRecomendada(J031tAccionRecomendada $v = null)
	{
		if ($v === null) {
			$this->setCoAccion(NULL);
		} else {
			$this->setCoAccion($v->getCoAccion());
		}

		$this->aJ031tAccionRecomendada = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the J031tAccionRecomendada object, it will not be re-added.
		if ($v !== null) {
			$v->addJ045tReferenciaMarco($this);
		}

		return $this;
	}


	/**
	 * Get the associated J031tAccionRecomendada object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     J031tAccionRecomendada The associated J031tAccionRecomendada object.
	 * @throws     PropelException
	 */
	public function getJ031tAccionRecomendada(PropelPDO $con = null)
	{
		if ($this->aJ031tAccionRecomendada === null && (($this->co_accion !== "" && $this->co_accion !== null))) {
			$c = new Criteria(J031tAccionRecomendadaPeer::DATABASE_NAME);
			$c->add(J031tAccionRecomendadaPeer::CO_ACCION, $this->co_accion);
			$this->aJ031tAccionRecomendada = J031tAccionRecomendadaPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aJ031tAccionRecomendada->addJ045tReferenciaMarcos($this);
			 */
		}
		return $this->aJ031tAccionRecomendada;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aJ046tMarcoNormativo = null;
			$this->aJ034tIncidente = null;
			$this->aJ030tInformeRecomendaciones = null;
			$this->aJ016tForense = null;
			$this->aJ031tAccionRecomendada = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseJ045tReferenciaMarco:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseJ045tReferenciaMarco::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseJ045tReferenciaMarco
