<?php

/**
 * Base class that represents a row from the 'j047t_documento_normativo' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu Nov 12 11:16:19 2015
 *
 * @package    lib.model.om
 */
abstract class BaseJ047tDocumentoNormativo extends BaseObject  implements Persistent {


  const PEER = 'J047tDocumentoNormativoPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        J047tDocumentoNormativoPeer
	 */
	protected static $peer;

	/**
	 * The value for the co_documento_normativo field.
	 * @var        string
	 */
	protected $co_documento_normativo;

	/**
	 * The value for the co_tipo_marco field.
	 * @var        string
	 */
	protected $co_tipo_marco;

	/**
	 * The value for the tx_titulo field.
	 * @var        string
	 */
	protected $tx_titulo;

	/**
	 * The value for the tx_descripcion field.
	 * @var        string
	 */
	protected $tx_descripcion;

	/**
	 * The value for the tx_revision field.
	 * @var        string
	 */
	protected $tx_revision;

	/**
	 * The value for the co_estado field.
	 * @var        string
	 */
	protected $co_estado;

	/**
	 * The value for the fe_aprueba1 field.
	 * @var        string
	 */
	protected $fe_aprueba1;

	/**
	 * The value for the co_aprueba1 field.
	 * @var        string
	 */
	protected $co_aprueba1;

	/**
	 * The value for the fe_aprueba2 field.
	 * @var        string
	 */
	protected $fe_aprueba2;

	/**
	 * The value for the co_aprueba2 field.
	 * @var        string
	 */
	protected $co_aprueba2;

	/**
	 * The value for the fe_elimina1 field.
	 * @var        string
	 */
	protected $fe_elimina1;

	/**
	 * The value for the co_elimina1 field.
	 * @var        string
	 */
	protected $co_elimina1;

	/**
	 * The value for the fe_elimina2 field.
	 * @var        string
	 */
	protected $fe_elimina2;

	/**
	 * The value for the co_elimina2 field.
	 * @var        string
	 */
	protected $co_elimina2;

	/**
	 * The value for the tx_observaciones field.
	 * @var        string
	 */
	protected $tx_observaciones;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the update_at field.
	 * @var        string
	 */
	protected $update_at;

	/**
	 * The value for the co_usuario_created field.
	 * @var        string
	 */
	protected $co_usuario_created;

	/**
	 * The value for the co_usuario_updated field.
	 * @var        string
	 */
	protected $co_usuario_updated;

	/**
	 * @var        J049tTipoMarco
	 */
	protected $aJ049tTipoMarco;

	/**
	 * @var        J048tEstadoDocumento
	 */
	protected $aJ048tEstadoDocumento;

	/**
	 * @var        J002tUsuario
	 */
	protected $aJ002tUsuarioRelatedByCoAprueba1;

	/**
	 * @var        J002tUsuario
	 */
	protected $aJ002tUsuarioRelatedByCoAprueba2;

	/**
	 * @var        J002tUsuario
	 */
	protected $aJ002tUsuarioRelatedByCoElimina1;

	/**
	 * @var        J002tUsuario
	 */
	protected $aJ002tUsuarioRelatedByCoElimina2;

	/**
	 * @var        J002tUsuario
	 */
	protected $aJ002tUsuarioRelatedByCoUsuarioCreated;

	/**
	 * @var        J002tUsuario
	 */
	protected $aJ002tUsuarioRelatedByCoUsuarioUpdated;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseJ047tDocumentoNormativo object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [co_documento_normativo] column value.
	 * 
	 * @return     string
	 */
	public function getCoDocumentoNormativo()
	{
		return $this->co_documento_normativo;
	}

	/**
	 * Get the [co_tipo_marco] column value.
	 * 
	 * @return     string
	 */
	public function getCoTipoMarco()
	{
		return $this->co_tipo_marco;
	}

	/**
	 * Get the [tx_titulo] column value.
	 * 
	 * @return     string
	 */
	public function getTxTitulo()
	{
		return $this->tx_titulo;
	}

	/**
	 * Get the [tx_descripcion] column value.
	 * 
	 * @return     string
	 */
	public function getTxDescripcion()
	{
		return $this->tx_descripcion;
	}

	/**
	 * Get the [tx_revision] column value.
	 * 
	 * @return     string
	 */
	public function getTxRevision()
	{
		return $this->tx_revision;
	}

	/**
	 * Get the [co_estado] column value.
	 * 
	 * @return     string
	 */
	public function getCoEstado()
	{
		return $this->co_estado;
	}

	/**
	 * Get the [optionally formatted] temporal [fe_aprueba1] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFeAprueba1($format = 'Y-m-d')
	{
		if ($this->fe_aprueba1 === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->fe_aprueba1);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fe_aprueba1, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [co_aprueba1] column value.
	 * 
	 * @return     string
	 */
	public function getCoAprueba1()
	{
		return $this->co_aprueba1;
	}

	/**
	 * Get the [optionally formatted] temporal [fe_aprueba2] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFeAprueba2($format = 'Y-m-d')
	{
		if ($this->fe_aprueba2 === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->fe_aprueba2);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fe_aprueba2, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [co_aprueba2] column value.
	 * 
	 * @return     string
	 */
	public function getCoAprueba2()
	{
		return $this->co_aprueba2;
	}

	/**
	 * Get the [optionally formatted] temporal [fe_elimina1] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFeElimina1($format = 'Y-m-d')
	{
		if ($this->fe_elimina1 === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->fe_elimina1);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fe_elimina1, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [co_elimina1] column value.
	 * 
	 * @return     string
	 */
	public function getCoElimina1()
	{
		return $this->co_elimina1;
	}

	/**
	 * Get the [optionally formatted] temporal [fe_elimina2] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFeElimina2($format = 'Y-m-d')
	{
		if ($this->fe_elimina2 === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->fe_elimina2);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fe_elimina2, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [co_elimina2] column value.
	 * 
	 * @return     string
	 */
	public function getCoElimina2()
	{
		return $this->co_elimina2;
	}

	/**
	 * Get the [tx_observaciones] column value.
	 * 
	 * @return     string
	 */
	public function getTxObservaciones()
	{
		return $this->tx_observaciones;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d')
	{
		if ($this->created_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->created_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [update_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdateAt($format = 'Y-m-d H:i:s')
	{
		if ($this->update_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->update_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->update_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [co_usuario_created] column value.
	 * 
	 * @return     string
	 */
	public function getCoUsuarioCreated()
	{
		return $this->co_usuario_created;
	}

	/**
	 * Get the [co_usuario_updated] column value.
	 * 
	 * @return     string
	 */
	public function getCoUsuarioUpdated()
	{
		return $this->co_usuario_updated;
	}

	/**
	 * Set the value of [co_documento_normativo] column.
	 * 
	 * @param      string $v new value
	 * @return     J047tDocumentoNormativo The current object (for fluent API support)
	 */
	public function setCoDocumentoNormativo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_documento_normativo !== $v) {
			$this->co_documento_normativo = $v;
			$this->modifiedColumns[] = J047tDocumentoNormativoPeer::CO_DOCUMENTO_NORMATIVO;
		}

		return $this;
	} // setCoDocumentoNormativo()

	/**
	 * Set the value of [co_tipo_marco] column.
	 * 
	 * @param      string $v new value
	 * @return     J047tDocumentoNormativo The current object (for fluent API support)
	 */
	public function setCoTipoMarco($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_tipo_marco !== $v) {
			$this->co_tipo_marco = $v;
			$this->modifiedColumns[] = J047tDocumentoNormativoPeer::CO_TIPO_MARCO;
		}

		if ($this->aJ049tTipoMarco !== null && $this->aJ049tTipoMarco->getCoTipoMarco() !== $v) {
			$this->aJ049tTipoMarco = null;
		}

		return $this;
	} // setCoTipoMarco()

	/**
	 * Set the value of [tx_titulo] column.
	 * 
	 * @param      string $v new value
	 * @return     J047tDocumentoNormativo The current object (for fluent API support)
	 */
	public function setTxTitulo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tx_titulo !== $v) {
			$this->tx_titulo = $v;
			$this->modifiedColumns[] = J047tDocumentoNormativoPeer::TX_TITULO;
		}

		return $this;
	} // setTxTitulo()

	/**
	 * Set the value of [tx_descripcion] column.
	 * 
	 * @param      string $v new value
	 * @return     J047tDocumentoNormativo The current object (for fluent API support)
	 */
	public function setTxDescripcion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tx_descripcion !== $v) {
			$this->tx_descripcion = $v;
			$this->modifiedColumns[] = J047tDocumentoNormativoPeer::TX_DESCRIPCION;
		}

		return $this;
	} // setTxDescripcion()

	/**
	 * Set the value of [tx_revision] column.
	 * 
	 * @param      string $v new value
	 * @return     J047tDocumentoNormativo The current object (for fluent API support)
	 */
	public function setTxRevision($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tx_revision !== $v) {
			$this->tx_revision = $v;
			$this->modifiedColumns[] = J047tDocumentoNormativoPeer::TX_REVISION;
		}

		return $this;
	} // setTxRevision()

	/**
	 * Set the value of [co_estado] column.
	 * 
	 * @param      string $v new value
	 * @return     J047tDocumentoNormativo The current object (for fluent API support)
	 */
	public function setCoEstado($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_estado !== $v) {
			$this->co_estado = $v;
			$this->modifiedColumns[] = J047tDocumentoNormativoPeer::CO_ESTADO;
		}

		if ($this->aJ048tEstadoDocumento !== null && $this->aJ048tEstadoDocumento->getCoEstadoDocumento() !== $v) {
			$this->aJ048tEstadoDocumento = null;
		}

		return $this;
	} // setCoEstado()

	/**
	 * Sets the value of [fe_aprueba1] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     J047tDocumentoNormativo The current object (for fluent API support)
	 */
	public function setFeAprueba1($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fe_aprueba1 !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fe_aprueba1 !== null && $tmpDt = new DateTime($this->fe_aprueba1)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fe_aprueba1 = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = J047tDocumentoNormativoPeer::FE_APRUEBA1;
			}
		} // if either are not null

		return $this;
	} // setFeAprueba1()

	/**
	 * Set the value of [co_aprueba1] column.
	 * 
	 * @param      string $v new value
	 * @return     J047tDocumentoNormativo The current object (for fluent API support)
	 */
	public function setCoAprueba1($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_aprueba1 !== $v) {
			$this->co_aprueba1 = $v;
			$this->modifiedColumns[] = J047tDocumentoNormativoPeer::CO_APRUEBA1;
		}

		if ($this->aJ002tUsuarioRelatedByCoAprueba1 !== null && $this->aJ002tUsuarioRelatedByCoAprueba1->getCoUsuario() !== $v) {
			$this->aJ002tUsuarioRelatedByCoAprueba1 = null;
		}

		return $this;
	} // setCoAprueba1()

	/**
	 * Sets the value of [fe_aprueba2] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     J047tDocumentoNormativo The current object (for fluent API support)
	 */
	public function setFeAprueba2($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fe_aprueba2 !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fe_aprueba2 !== null && $tmpDt = new DateTime($this->fe_aprueba2)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fe_aprueba2 = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = J047tDocumentoNormativoPeer::FE_APRUEBA2;
			}
		} // if either are not null

		return $this;
	} // setFeAprueba2()

	/**
	 * Set the value of [co_aprueba2] column.
	 * 
	 * @param      string $v new value
	 * @return     J047tDocumentoNormativo The current object (for fluent API support)
	 */
	public function setCoAprueba2($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_aprueba2 !== $v) {
			$this->co_aprueba2 = $v;
			$this->modifiedColumns[] = J047tDocumentoNormativoPeer::CO_APRUEBA2;
		}

		if ($this->aJ002tUsuarioRelatedByCoAprueba2 !== null && $this->aJ002tUsuarioRelatedByCoAprueba2->getCoUsuario() !== $v) {
			$this->aJ002tUsuarioRelatedByCoAprueba2 = null;
		}

		return $this;
	} // setCoAprueba2()

	/**
	 * Sets the value of [fe_elimina1] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     J047tDocumentoNormativo The current object (for fluent API support)
	 */
	public function setFeElimina1($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fe_elimina1 !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fe_elimina1 !== null && $tmpDt = new DateTime($this->fe_elimina1)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fe_elimina1 = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = J047tDocumentoNormativoPeer::FE_ELIMINA1;
			}
		} // if either are not null

		return $this;
	} // setFeElimina1()

	/**
	 * Set the value of [co_elimina1] column.
	 * 
	 * @param      string $v new value
	 * @return     J047tDocumentoNormativo The current object (for fluent API support)
	 */
	public function setCoElimina1($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_elimina1 !== $v) {
			$this->co_elimina1 = $v;
			$this->modifiedColumns[] = J047tDocumentoNormativoPeer::CO_ELIMINA1;
		}

		if ($this->aJ002tUsuarioRelatedByCoElimina1 !== null && $this->aJ002tUsuarioRelatedByCoElimina1->getCoUsuario() !== $v) {
			$this->aJ002tUsuarioRelatedByCoElimina1 = null;
		}

		return $this;
	} // setCoElimina1()

	/**
	 * Sets the value of [fe_elimina2] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     J047tDocumentoNormativo The current object (for fluent API support)
	 */
	public function setFeElimina2($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fe_elimina2 !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fe_elimina2 !== null && $tmpDt = new DateTime($this->fe_elimina2)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fe_elimina2 = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = J047tDocumentoNormativoPeer::FE_ELIMINA2;
			}
		} // if either are not null

		return $this;
	} // setFeElimina2()

	/**
	 * Set the value of [co_elimina2] column.
	 * 
	 * @param      string $v new value
	 * @return     J047tDocumentoNormativo The current object (for fluent API support)
	 */
	public function setCoElimina2($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_elimina2 !== $v) {
			$this->co_elimina2 = $v;
			$this->modifiedColumns[] = J047tDocumentoNormativoPeer::CO_ELIMINA2;
		}

		if ($this->aJ002tUsuarioRelatedByCoElimina2 !== null && $this->aJ002tUsuarioRelatedByCoElimina2->getCoUsuario() !== $v) {
			$this->aJ002tUsuarioRelatedByCoElimina2 = null;
		}

		return $this;
	} // setCoElimina2()

	/**
	 * Set the value of [tx_observaciones] column.
	 * 
	 * @param      string $v new value
	 * @return     J047tDocumentoNormativo The current object (for fluent API support)
	 */
	public function setTxObservaciones($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tx_observaciones !== $v) {
			$this->tx_observaciones = $v;
			$this->modifiedColumns[] = J047tDocumentoNormativoPeer::TX_OBSERVACIONES;
		}

		return $this;
	} // setTxObservaciones()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     J047tDocumentoNormativo The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = J047tDocumentoNormativoPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [update_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     J047tDocumentoNormativo The current object (for fluent API support)
	 */
	public function setUpdateAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->update_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->update_at !== null && $tmpDt = new DateTime($this->update_at)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->update_at = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = J047tDocumentoNormativoPeer::UPDATE_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdateAt()

	/**
	 * Set the value of [co_usuario_created] column.
	 * 
	 * @param      string $v new value
	 * @return     J047tDocumentoNormativo The current object (for fluent API support)
	 */
	public function setCoUsuarioCreated($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_usuario_created !== $v) {
			$this->co_usuario_created = $v;
			$this->modifiedColumns[] = J047tDocumentoNormativoPeer::CO_USUARIO_CREATED;
		}

		if ($this->aJ002tUsuarioRelatedByCoUsuarioCreated !== null && $this->aJ002tUsuarioRelatedByCoUsuarioCreated->getCoUsuario() !== $v) {
			$this->aJ002tUsuarioRelatedByCoUsuarioCreated = null;
		}

		return $this;
	} // setCoUsuarioCreated()

	/**
	 * Set the value of [co_usuario_updated] column.
	 * 
	 * @param      string $v new value
	 * @return     J047tDocumentoNormativo The current object (for fluent API support)
	 */
	public function setCoUsuarioUpdated($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_usuario_updated !== $v) {
			$this->co_usuario_updated = $v;
			$this->modifiedColumns[] = J047tDocumentoNormativoPeer::CO_USUARIO_UPDATED;
		}

		if ($this->aJ002tUsuarioRelatedByCoUsuarioUpdated !== null && $this->aJ002tUsuarioRelatedByCoUsuarioUpdated->getCoUsuario() !== $v) {
			$this->aJ002tUsuarioRelatedByCoUsuarioUpdated = null;
		}

		return $this;
	} // setCoUsuarioUpdated()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->co_documento_normativo = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
			$this->co_tipo_marco = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->tx_titulo = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->tx_descripcion = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->tx_revision = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->co_estado = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->fe_aprueba1 = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->co_aprueba1 = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->fe_aprueba2 = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->co_aprueba2 = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->fe_elimina1 = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->co_elimina1 = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->fe_elimina2 = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->co_elimina2 = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->tx_observaciones = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->created_at = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->update_at = ($row[$startcol + 16] !== null) ? (string) $row[$startcol + 16] : null;
			$this->co_usuario_created = ($row[$startcol + 17] !== null) ? (string) $row[$startcol + 17] : null;
			$this->co_usuario_updated = ($row[$startcol + 18] !== null) ? (string) $row[$startcol + 18] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 19; // 19 = J047tDocumentoNormativoPeer::NUM_COLUMNS - J047tDocumentoNormativoPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating J047tDocumentoNormativo object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aJ049tTipoMarco !== null && $this->co_tipo_marco !== $this->aJ049tTipoMarco->getCoTipoMarco()) {
			$this->aJ049tTipoMarco = null;
		}
		if ($this->aJ048tEstadoDocumento !== null && $this->co_estado !== $this->aJ048tEstadoDocumento->getCoEstadoDocumento()) {
			$this->aJ048tEstadoDocumento = null;
		}
		if ($this->aJ002tUsuarioRelatedByCoAprueba1 !== null && $this->co_aprueba1 !== $this->aJ002tUsuarioRelatedByCoAprueba1->getCoUsuario()) {
			$this->aJ002tUsuarioRelatedByCoAprueba1 = null;
		}
		if ($this->aJ002tUsuarioRelatedByCoAprueba2 !== null && $this->co_aprueba2 !== $this->aJ002tUsuarioRelatedByCoAprueba2->getCoUsuario()) {
			$this->aJ002tUsuarioRelatedByCoAprueba2 = null;
		}
		if ($this->aJ002tUsuarioRelatedByCoElimina1 !== null && $this->co_elimina1 !== $this->aJ002tUsuarioRelatedByCoElimina1->getCoUsuario()) {
			$this->aJ002tUsuarioRelatedByCoElimina1 = null;
		}
		if ($this->aJ002tUsuarioRelatedByCoElimina2 !== null && $this->co_elimina2 !== $this->aJ002tUsuarioRelatedByCoElimina2->getCoUsuario()) {
			$this->aJ002tUsuarioRelatedByCoElimina2 = null;
		}
		if ($this->aJ002tUsuarioRelatedByCoUsuarioCreated !== null && $this->co_usuario_created !== $this->aJ002tUsuarioRelatedByCoUsuarioCreated->getCoUsuario()) {
			$this->aJ002tUsuarioRelatedByCoUsuarioCreated = null;
		}
		if ($this->aJ002tUsuarioRelatedByCoUsuarioUpdated !== null && $this->co_usuario_updated !== $this->aJ002tUsuarioRelatedByCoUsuarioUpdated->getCoUsuario()) {
			$this->aJ002tUsuarioRelatedByCoUsuarioUpdated = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(J047tDocumentoNormativoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = J047tDocumentoNormativoPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aJ049tTipoMarco = null;
			$this->aJ048tEstadoDocumento = null;
			$this->aJ002tUsuarioRelatedByCoAprueba1 = null;
			$this->aJ002tUsuarioRelatedByCoAprueba2 = null;
			$this->aJ002tUsuarioRelatedByCoElimina1 = null;
			$this->aJ002tUsuarioRelatedByCoElimina2 = null;
			$this->aJ002tUsuarioRelatedByCoUsuarioCreated = null;
			$this->aJ002tUsuarioRelatedByCoUsuarioUpdated = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseJ047tDocumentoNormativo:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(J047tDocumentoNormativoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			J047tDocumentoNormativoPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseJ047tDocumentoNormativo:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseJ047tDocumentoNormativo:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(J047tDocumentoNormativoPeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(J047tDocumentoNormativoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseJ047tDocumentoNormativo:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			J047tDocumentoNormativoPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aJ049tTipoMarco !== null) {
				if ($this->aJ049tTipoMarco->isModified() || $this->aJ049tTipoMarco->isNew()) {
					$affectedRows += $this->aJ049tTipoMarco->save($con);
				}
				$this->setJ049tTipoMarco($this->aJ049tTipoMarco);
			}

			if ($this->aJ048tEstadoDocumento !== null) {
				if ($this->aJ048tEstadoDocumento->isModified() || $this->aJ048tEstadoDocumento->isNew()) {
					$affectedRows += $this->aJ048tEstadoDocumento->save($con);
				}
				$this->setJ048tEstadoDocumento($this->aJ048tEstadoDocumento);
			}

			if ($this->aJ002tUsuarioRelatedByCoAprueba1 !== null) {
				if ($this->aJ002tUsuarioRelatedByCoAprueba1->isModified() || $this->aJ002tUsuarioRelatedByCoAprueba1->isNew()) {
					$affectedRows += $this->aJ002tUsuarioRelatedByCoAprueba1->save($con);
				}
				$this->setJ002tUsuarioRelatedByCoAprueba1($this->aJ002tUsuarioRelatedByCoAprueba1);
			}

			if ($this->aJ002tUsuarioRelatedByCoAprueba2 !== null) {
				if ($this->aJ002tUsuarioRelatedByCoAprueba2->isModified() || $this->aJ002tUsuarioRelatedByCoAprueba2->isNew()) {
					$affectedRows += $this->aJ002tUsuarioRelatedByCoAprueba2->save($con);
				}
				$this->setJ002tUsuarioRelatedByCoAprueba2($this->aJ002tUsuarioRelatedByCoAprueba2);
			}

			if ($this->aJ002tUsuarioRelatedByCoElimina1 !== null) {
				if ($this->aJ002tUsuarioRelatedByCoElimina1->isModified() || $this->aJ002tUsuarioRelatedByCoElimina1->isNew()) {
					$affectedRows += $this->aJ002tUsuarioRelatedByCoElimina1->save($con);
				}
				$this->setJ002tUsuarioRelatedByCoElimina1($this->aJ002tUsuarioRelatedByCoElimina1);
			}

			if ($this->aJ002tUsuarioRelatedByCoElimina2 !== null) {
				if ($this->aJ002tUsuarioRelatedByCoElimina2->isModified() || $this->aJ002tUsuarioRelatedByCoElimina2->isNew()) {
					$affectedRows += $this->aJ002tUsuarioRelatedByCoElimina2->save($con);
				}
				$this->setJ002tUsuarioRelatedByCoElimina2($this->aJ002tUsuarioRelatedByCoElimina2);
			}

			if ($this->aJ002tUsuarioRelatedByCoUsuarioCreated !== null) {
				if ($this->aJ002tUsuarioRelatedByCoUsuarioCreated->isModified() || $this->aJ002tUsuarioRelatedByCoUsuarioCreated->isNew()) {
					$affectedRows += $this->aJ002tUsuarioRelatedByCoUsuarioCreated->save($con);
				}
				$this->setJ002tUsuarioRelatedByCoUsuarioCreated($this->aJ002tUsuarioRelatedByCoUsuarioCreated);
			}

			if ($this->aJ002tUsuarioRelatedByCoUsuarioUpdated !== null) {
				if ($this->aJ002tUsuarioRelatedByCoUsuarioUpdated->isModified() || $this->aJ002tUsuarioRelatedByCoUsuarioUpdated->isNew()) {
					$affectedRows += $this->aJ002tUsuarioRelatedByCoUsuarioUpdated->save($con);
				}
				$this->setJ002tUsuarioRelatedByCoUsuarioUpdated($this->aJ002tUsuarioRelatedByCoUsuarioUpdated);
			}


			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = J047tDocumentoNormativoPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setNew(false);
				} else {
					$affectedRows += J047tDocumentoNormativoPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aJ049tTipoMarco !== null) {
				if (!$this->aJ049tTipoMarco->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aJ049tTipoMarco->getValidationFailures());
				}
			}

			if ($this->aJ048tEstadoDocumento !== null) {
				if (!$this->aJ048tEstadoDocumento->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aJ048tEstadoDocumento->getValidationFailures());
				}
			}

			if ($this->aJ002tUsuarioRelatedByCoAprueba1 !== null) {
				if (!$this->aJ002tUsuarioRelatedByCoAprueba1->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aJ002tUsuarioRelatedByCoAprueba1->getValidationFailures());
				}
			}

			if ($this->aJ002tUsuarioRelatedByCoAprueba2 !== null) {
				if (!$this->aJ002tUsuarioRelatedByCoAprueba2->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aJ002tUsuarioRelatedByCoAprueba2->getValidationFailures());
				}
			}

			if ($this->aJ002tUsuarioRelatedByCoElimina1 !== null) {
				if (!$this->aJ002tUsuarioRelatedByCoElimina1->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aJ002tUsuarioRelatedByCoElimina1->getValidationFailures());
				}
			}

			if ($this->aJ002tUsuarioRelatedByCoElimina2 !== null) {
				if (!$this->aJ002tUsuarioRelatedByCoElimina2->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aJ002tUsuarioRelatedByCoElimina2->getValidationFailures());
				}
			}

			if ($this->aJ002tUsuarioRelatedByCoUsuarioCreated !== null) {
				if (!$this->aJ002tUsuarioRelatedByCoUsuarioCreated->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aJ002tUsuarioRelatedByCoUsuarioCreated->getValidationFailures());
				}
			}

			if ($this->aJ002tUsuarioRelatedByCoUsuarioUpdated !== null) {
				if (!$this->aJ002tUsuarioRelatedByCoUsuarioUpdated->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aJ002tUsuarioRelatedByCoUsuarioUpdated->getValidationFailures());
				}
			}


			if (($retval = J047tDocumentoNormativoPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = J047tDocumentoNormativoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getCoDocumentoNormativo();
				break;
			case 1:
				return $this->getCoTipoMarco();
				break;
			case 2:
				return $this->getTxTitulo();
				break;
			case 3:
				return $this->getTxDescripcion();
				break;
			case 4:
				return $this->getTxRevision();
				break;
			case 5:
				return $this->getCoEstado();
				break;
			case 6:
				return $this->getFeAprueba1();
				break;
			case 7:
				return $this->getCoAprueba1();
				break;
			case 8:
				return $this->getFeAprueba2();
				break;
			case 9:
				return $this->getCoAprueba2();
				break;
			case 10:
				return $this->getFeElimina1();
				break;
			case 11:
				return $this->getCoElimina1();
				break;
			case 12:
				return $this->getFeElimina2();
				break;
			case 13:
				return $this->getCoElimina2();
				break;
			case 14:
				return $this->getTxObservaciones();
				break;
			case 15:
				return $this->getCreatedAt();
				break;
			case 16:
				return $this->getUpdateAt();
				break;
			case 17:
				return $this->getCoUsuarioCreated();
				break;
			case 18:
				return $this->getCoUsuarioUpdated();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = J047tDocumentoNormativoPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getCoDocumentoNormativo(),
			$keys[1] => $this->getCoTipoMarco(),
			$keys[2] => $this->getTxTitulo(),
			$keys[3] => $this->getTxDescripcion(),
			$keys[4] => $this->getTxRevision(),
			$keys[5] => $this->getCoEstado(),
			$keys[6] => $this->getFeAprueba1(),
			$keys[7] => $this->getCoAprueba1(),
			$keys[8] => $this->getFeAprueba2(),
			$keys[9] => $this->getCoAprueba2(),
			$keys[10] => $this->getFeElimina1(),
			$keys[11] => $this->getCoElimina1(),
			$keys[12] => $this->getFeElimina2(),
			$keys[13] => $this->getCoElimina2(),
			$keys[14] => $this->getTxObservaciones(),
			$keys[15] => $this->getCreatedAt(),
			$keys[16] => $this->getUpdateAt(),
			$keys[17] => $this->getCoUsuarioCreated(),
			$keys[18] => $this->getCoUsuarioUpdated(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = J047tDocumentoNormativoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setCoDocumentoNormativo($value);
				break;
			case 1:
				$this->setCoTipoMarco($value);
				break;
			case 2:
				$this->setTxTitulo($value);
				break;
			case 3:
				$this->setTxDescripcion($value);
				break;
			case 4:
				$this->setTxRevision($value);
				break;
			case 5:
				$this->setCoEstado($value);
				break;
			case 6:
				$this->setFeAprueba1($value);
				break;
			case 7:
				$this->setCoAprueba1($value);
				break;
			case 8:
				$this->setFeAprueba2($value);
				break;
			case 9:
				$this->setCoAprueba2($value);
				break;
			case 10:
				$this->setFeElimina1($value);
				break;
			case 11:
				$this->setCoElimina1($value);
				break;
			case 12:
				$this->setFeElimina2($value);
				break;
			case 13:
				$this->setCoElimina2($value);
				break;
			case 14:
				$this->setTxObservaciones($value);
				break;
			case 15:
				$this->setCreatedAt($value);
				break;
			case 16:
				$this->setUpdateAt($value);
				break;
			case 17:
				$this->setCoUsuarioCreated($value);
				break;
			case 18:
				$this->setCoUsuarioUpdated($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = J047tDocumentoNormativoPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setCoDocumentoNormativo($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setCoTipoMarco($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setTxTitulo($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setTxDescripcion($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setTxRevision($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setCoEstado($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setFeAprueba1($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setCoAprueba1($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setFeAprueba2($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setCoAprueba2($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setFeElimina1($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setCoElimina1($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setFeElimina2($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setCoElimina2($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setTxObservaciones($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setCreatedAt($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setUpdateAt($arr[$keys[16]]);
		if (array_key_exists($keys[17], $arr)) $this->setCoUsuarioCreated($arr[$keys[17]]);
		if (array_key_exists($keys[18], $arr)) $this->setCoUsuarioUpdated($arr[$keys[18]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(J047tDocumentoNormativoPeer::DATABASE_NAME);

		if ($this->isColumnModified(J047tDocumentoNormativoPeer::CO_DOCUMENTO_NORMATIVO)) $criteria->add(J047tDocumentoNormativoPeer::CO_DOCUMENTO_NORMATIVO, $this->co_documento_normativo);
		if ($this->isColumnModified(J047tDocumentoNormativoPeer::CO_TIPO_MARCO)) $criteria->add(J047tDocumentoNormativoPeer::CO_TIPO_MARCO, $this->co_tipo_marco);
		if ($this->isColumnModified(J047tDocumentoNormativoPeer::TX_TITULO)) $criteria->add(J047tDocumentoNormativoPeer::TX_TITULO, $this->tx_titulo);
		if ($this->isColumnModified(J047tDocumentoNormativoPeer::TX_DESCRIPCION)) $criteria->add(J047tDocumentoNormativoPeer::TX_DESCRIPCION, $this->tx_descripcion);
		if ($this->isColumnModified(J047tDocumentoNormativoPeer::TX_REVISION)) $criteria->add(J047tDocumentoNormativoPeer::TX_REVISION, $this->tx_revision);
		if ($this->isColumnModified(J047tDocumentoNormativoPeer::CO_ESTADO)) $criteria->add(J047tDocumentoNormativoPeer::CO_ESTADO, $this->co_estado);
		if ($this->isColumnModified(J047tDocumentoNormativoPeer::FE_APRUEBA1)) $criteria->add(J047tDocumentoNormativoPeer::FE_APRUEBA1, $this->fe_aprueba1);
		if ($this->isColumnModified(J047tDocumentoNormativoPeer::CO_APRUEBA1)) $criteria->add(J047tDocumentoNormativoPeer::CO_APRUEBA1, $this->co_aprueba1);
		if ($this->isColumnModified(J047tDocumentoNormativoPeer::FE_APRUEBA2)) $criteria->add(J047tDocumentoNormativoPeer::FE_APRUEBA2, $this->fe_aprueba2);
		if ($this->isColumnModified(J047tDocumentoNormativoPeer::CO_APRUEBA2)) $criteria->add(J047tDocumentoNormativoPeer::CO_APRUEBA2, $this->co_aprueba2);
		if ($this->isColumnModified(J047tDocumentoNormativoPeer::FE_ELIMINA1)) $criteria->add(J047tDocumentoNormativoPeer::FE_ELIMINA1, $this->fe_elimina1);
		if ($this->isColumnModified(J047tDocumentoNormativoPeer::CO_ELIMINA1)) $criteria->add(J047tDocumentoNormativoPeer::CO_ELIMINA1, $this->co_elimina1);
		if ($this->isColumnModified(J047tDocumentoNormativoPeer::FE_ELIMINA2)) $criteria->add(J047tDocumentoNormativoPeer::FE_ELIMINA2, $this->fe_elimina2);
		if ($this->isColumnModified(J047tDocumentoNormativoPeer::CO_ELIMINA2)) $criteria->add(J047tDocumentoNormativoPeer::CO_ELIMINA2, $this->co_elimina2);
		if ($this->isColumnModified(J047tDocumentoNormativoPeer::TX_OBSERVACIONES)) $criteria->add(J047tDocumentoNormativoPeer::TX_OBSERVACIONES, $this->tx_observaciones);
		if ($this->isColumnModified(J047tDocumentoNormativoPeer::CREATED_AT)) $criteria->add(J047tDocumentoNormativoPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(J047tDocumentoNormativoPeer::UPDATE_AT)) $criteria->add(J047tDocumentoNormativoPeer::UPDATE_AT, $this->update_at);
		if ($this->isColumnModified(J047tDocumentoNormativoPeer::CO_USUARIO_CREATED)) $criteria->add(J047tDocumentoNormativoPeer::CO_USUARIO_CREATED, $this->co_usuario_created);
		if ($this->isColumnModified(J047tDocumentoNormativoPeer::CO_USUARIO_UPDATED)) $criteria->add(J047tDocumentoNormativoPeer::CO_USUARIO_UPDATED, $this->co_usuario_updated);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(J047tDocumentoNormativoPeer::DATABASE_NAME);

		$criteria->add(J047tDocumentoNormativoPeer::CO_DOCUMENTO_NORMATIVO, $this->co_documento_normativo);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     string
	 */
	public function getPrimaryKey()
	{
		return $this->getCoDocumentoNormativo();
	}

	/**
	 * Generic method to set the primary key (co_documento_normativo column).
	 *
	 * @param      string $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setCoDocumentoNormativo($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of J047tDocumentoNormativo (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setCoDocumentoNormativo($this->co_documento_normativo);

		$copyObj->setCoTipoMarco($this->co_tipo_marco);

		$copyObj->setTxTitulo($this->tx_titulo);

		$copyObj->setTxDescripcion($this->tx_descripcion);

		$copyObj->setTxRevision($this->tx_revision);

		$copyObj->setCoEstado($this->co_estado);

		$copyObj->setFeAprueba1($this->fe_aprueba1);

		$copyObj->setCoAprueba1($this->co_aprueba1);

		$copyObj->setFeAprueba2($this->fe_aprueba2);

		$copyObj->setCoAprueba2($this->co_aprueba2);

		$copyObj->setFeElimina1($this->fe_elimina1);

		$copyObj->setCoElimina1($this->co_elimina1);

		$copyObj->setFeElimina2($this->fe_elimina2);

		$copyObj->setCoElimina2($this->co_elimina2);

		$copyObj->setTxObservaciones($this->tx_observaciones);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdateAt($this->update_at);

		$copyObj->setCoUsuarioCreated($this->co_usuario_created);

		$copyObj->setCoUsuarioUpdated($this->co_usuario_updated);


		$copyObj->setNew(true);

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     J047tDocumentoNormativo Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     J047tDocumentoNormativoPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new J047tDocumentoNormativoPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a J049tTipoMarco object.
	 *
	 * @param      J049tTipoMarco $v
	 * @return     J047tDocumentoNormativo The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setJ049tTipoMarco(J049tTipoMarco $v = null)
	{
		if ($v === null) {
			$this->setCoTipoMarco(NULL);
		} else {
			$this->setCoTipoMarco($v->getCoTipoMarco());
		}

		$this->aJ049tTipoMarco = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the J049tTipoMarco object, it will not be re-added.
		if ($v !== null) {
			$v->addJ047tDocumentoNormativo($this);
		}

		return $this;
	}


	/**
	 * Get the associated J049tTipoMarco object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     J049tTipoMarco The associated J049tTipoMarco object.
	 * @throws     PropelException
	 */
	public function getJ049tTipoMarco(PropelPDO $con = null)
	{
		if ($this->aJ049tTipoMarco === null && (($this->co_tipo_marco !== "" && $this->co_tipo_marco !== null))) {
			$c = new Criteria(J049tTipoMarcoPeer::DATABASE_NAME);
			$c->add(J049tTipoMarcoPeer::CO_TIPO_MARCO, $this->co_tipo_marco);
			$this->aJ049tTipoMarco = J049tTipoMarcoPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aJ049tTipoMarco->addJ047tDocumentoNormativos($this);
			 */
		}
		return $this->aJ049tTipoMarco;
	}

	/**
	 * Declares an association between this object and a J048tEstadoDocumento object.
	 *
	 * @param      J048tEstadoDocumento $v
	 * @return     J047tDocumentoNormativo The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setJ048tEstadoDocumento(J048tEstadoDocumento $v = null)
	{
		if ($v === null) {
			$this->setCoEstado(NULL);
		} else {
			$this->setCoEstado($v->getCoEstadoDocumento());
		}

		$this->aJ048tEstadoDocumento = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the J048tEstadoDocumento object, it will not be re-added.
		if ($v !== null) {
			$v->addJ047tDocumentoNormativo($this);
		}

		return $this;
	}


	/**
	 * Get the associated J048tEstadoDocumento object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     J048tEstadoDocumento The associated J048tEstadoDocumento object.
	 * @throws     PropelException
	 */
	public function getJ048tEstadoDocumento(PropelPDO $con = null)
	{
		if ($this->aJ048tEstadoDocumento === null && (($this->co_estado !== "" && $this->co_estado !== null))) {
			$c = new Criteria(J048tEstadoDocumentoPeer::DATABASE_NAME);
			$c->add(J048tEstadoDocumentoPeer::CO_ESTADO_DOCUMENTO, $this->co_estado);
			$this->aJ048tEstadoDocumento = J048tEstadoDocumentoPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aJ048tEstadoDocumento->addJ047tDocumentoNormativos($this);
			 */
		}
		return $this->aJ048tEstadoDocumento;
	}

	/**
	 * Declares an association between this object and a J002tUsuario object.
	 *
	 * @param      J002tUsuario $v
	 * @return     J047tDocumentoNormativo The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setJ002tUsuarioRelatedByCoAprueba1(J002tUsuario $v = null)
	{
		if ($v === null) {
			$this->setCoAprueba1(NULL);
		} else {
			$this->setCoAprueba1($v->getCoUsuario());
		}

		$this->aJ002tUsuarioRelatedByCoAprueba1 = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the J002tUsuario object, it will not be re-added.
		if ($v !== null) {
			$v->addJ047tDocumentoNormativoRelatedByCoAprueba1($this);
		}

		return $this;
	}


	/**
	 * Get the associated J002tUsuario object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     J002tUsuario The associated J002tUsuario object.
	 * @throws     PropelException
	 */
	public function getJ002tUsuarioRelatedByCoAprueba1(PropelPDO $con = null)
	{
		if ($this->aJ002tUsuarioRelatedByCoAprueba1 === null && (($this->co_aprueba1 !== "" && $this->co_aprueba1 !== null))) {
			$c = new Criteria(J002tUsuarioPeer::DATABASE_NAME);
			$c->add(J002tUsuarioPeer::CO_USUARIO, $this->co_aprueba1);
			$this->aJ002tUsuarioRelatedByCoAprueba1 = J002tUsuarioPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aJ002tUsuarioRelatedByCoAprueba1->addJ047tDocumentoNormativosRelatedByCoAprueba1($this);
			 */
		}
		return $this->aJ002tUsuarioRelatedByCoAprueba1;
	}

	/**
	 * Declares an association between this object and a J002tUsuario object.
	 *
	 * @param      J002tUsuario $v
	 * @return     J047tDocumentoNormativo The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setJ002tUsuarioRelatedByCoAprueba2(J002tUsuario $v = null)
	{
		if ($v === null) {
			$this->setCoAprueba2(NULL);
		} else {
			$this->setCoAprueba2($v->getCoUsuario());
		}

		$this->aJ002tUsuarioRelatedByCoAprueba2 = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the J002tUsuario object, it will not be re-added.
		if ($v !== null) {
			$v->addJ047tDocumentoNormativoRelatedByCoAprueba2($this);
		}

		return $this;
	}


	/**
	 * Get the associated J002tUsuario object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     J002tUsuario The associated J002tUsuario object.
	 * @throws     PropelException
	 */
	public function getJ002tUsuarioRelatedByCoAprueba2(PropelPDO $con = null)
	{
		if ($this->aJ002tUsuarioRelatedByCoAprueba2 === null && (($this->co_aprueba2 !== "" && $this->co_aprueba2 !== null))) {
			$c = new Criteria(J002tUsuarioPeer::DATABASE_NAME);
			$c->add(J002tUsuarioPeer::CO_USUARIO, $this->co_aprueba2);
			$this->aJ002tUsuarioRelatedByCoAprueba2 = J002tUsuarioPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aJ002tUsuarioRelatedByCoAprueba2->addJ047tDocumentoNormativosRelatedByCoAprueba2($this);
			 */
		}
		return $this->aJ002tUsuarioRelatedByCoAprueba2;
	}

	/**
	 * Declares an association between this object and a J002tUsuario object.
	 *
	 * @param      J002tUsuario $v
	 * @return     J047tDocumentoNormativo The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setJ002tUsuarioRelatedByCoElimina1(J002tUsuario $v = null)
	{
		if ($v === null) {
			$this->setCoElimina1(NULL);
		} else {
			$this->setCoElimina1($v->getCoUsuario());
		}

		$this->aJ002tUsuarioRelatedByCoElimina1 = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the J002tUsuario object, it will not be re-added.
		if ($v !== null) {
			$v->addJ047tDocumentoNormativoRelatedByCoElimina1($this);
		}

		return $this;
	}


	/**
	 * Get the associated J002tUsuario object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     J002tUsuario The associated J002tUsuario object.
	 * @throws     PropelException
	 */
	public function getJ002tUsuarioRelatedByCoElimina1(PropelPDO $con = null)
	{
		if ($this->aJ002tUsuarioRelatedByCoElimina1 === null && (($this->co_elimina1 !== "" && $this->co_elimina1 !== null))) {
			$c = new Criteria(J002tUsuarioPeer::DATABASE_NAME);
			$c->add(J002tUsuarioPeer::CO_USUARIO, $this->co_elimina1);
			$this->aJ002tUsuarioRelatedByCoElimina1 = J002tUsuarioPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aJ002tUsuarioRelatedByCoElimina1->addJ047tDocumentoNormativosRelatedByCoElimina1($this);
			 */
		}
		return $this->aJ002tUsuarioRelatedByCoElimina1;
	}

	/**
	 * Declares an association between this object and a J002tUsuario object.
	 *
	 * @param      J002tUsuario $v
	 * @return     J047tDocumentoNormativo The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setJ002tUsuarioRelatedByCoElimina2(J002tUsuario $v = null)
	{
		if ($v === null) {
			$this->setCoElimina2(NULL);
		} else {
			$this->setCoElimina2($v->getCoUsuario());
		}

		$this->aJ002tUsuarioRelatedByCoElimina2 = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the J002tUsuario object, it will not be re-added.
		if ($v !== null) {
			$v->addJ047tDocumentoNormativoRelatedByCoElimina2($this);
		}

		return $this;
	}


	/**
	 * Get the associated J002tUsuario object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     J002tUsuario The associated J002tUsuario object.
	 * @throws     PropelException
	 */
	public function getJ002tUsuarioRelatedByCoElimina2(PropelPDO $con = null)
	{
		if ($this->aJ002tUsuarioRelatedByCoElimina2 === null && (($this->co_elimina2 !== "" && $this->co_elimina2 !== null))) {
			$c = new Criteria(J002tUsuarioPeer::DATABASE_NAME);
			$c->add(J002tUsuarioPeer::CO_USUARIO, $this->co_elimina2);
			$this->aJ002tUsuarioRelatedByCoElimina2 = J002tUsuarioPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aJ002tUsuarioRelatedByCoElimina2->addJ047tDocumentoNormativosRelatedByCoElimina2($this);
			 */
		}
		return $this->aJ002tUsuarioRelatedByCoElimina2;
	}

	/**
	 * Declares an association between this object and a J002tUsuario object.
	 *
	 * @param      J002tUsuario $v
	 * @return     J047tDocumentoNormativo The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setJ002tUsuarioRelatedByCoUsuarioCreated(J002tUsuario $v = null)
	{
		if ($v === null) {
			$this->setCoUsuarioCreated(NULL);
		} else {
			$this->setCoUsuarioCreated($v->getCoUsuario());
		}

		$this->aJ002tUsuarioRelatedByCoUsuarioCreated = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the J002tUsuario object, it will not be re-added.
		if ($v !== null) {
			$v->addJ047tDocumentoNormativoRelatedByCoUsuarioCreated($this);
		}

		return $this;
	}


	/**
	 * Get the associated J002tUsuario object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     J002tUsuario The associated J002tUsuario object.
	 * @throws     PropelException
	 */
	public function getJ002tUsuarioRelatedByCoUsuarioCreated(PropelPDO $con = null)
	{
		if ($this->aJ002tUsuarioRelatedByCoUsuarioCreated === null && (($this->co_usuario_created !== "" && $this->co_usuario_created !== null))) {
			$c = new Criteria(J002tUsuarioPeer::DATABASE_NAME);
			$c->add(J002tUsuarioPeer::CO_USUARIO, $this->co_usuario_created);
			$this->aJ002tUsuarioRelatedByCoUsuarioCreated = J002tUsuarioPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aJ002tUsuarioRelatedByCoUsuarioCreated->addJ047tDocumentoNormativosRelatedByCoUsuarioCreated($this);
			 */
		}
		return $this->aJ002tUsuarioRelatedByCoUsuarioCreated;
	}

	/**
	 * Declares an association between this object and a J002tUsuario object.
	 *
	 * @param      J002tUsuario $v
	 * @return     J047tDocumentoNormativo The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setJ002tUsuarioRelatedByCoUsuarioUpdated(J002tUsuario $v = null)
	{
		if ($v === null) {
			$this->setCoUsuarioUpdated(NULL);
		} else {
			$this->setCoUsuarioUpdated($v->getCoUsuario());
		}

		$this->aJ002tUsuarioRelatedByCoUsuarioUpdated = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the J002tUsuario object, it will not be re-added.
		if ($v !== null) {
			$v->addJ047tDocumentoNormativoRelatedByCoUsuarioUpdated($this);
		}

		return $this;
	}


	/**
	 * Get the associated J002tUsuario object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     J002tUsuario The associated J002tUsuario object.
	 * @throws     PropelException
	 */
	public function getJ002tUsuarioRelatedByCoUsuarioUpdated(PropelPDO $con = null)
	{
		if ($this->aJ002tUsuarioRelatedByCoUsuarioUpdated === null && (($this->co_usuario_updated !== "" && $this->co_usuario_updated !== null))) {
			$c = new Criteria(J002tUsuarioPeer::DATABASE_NAME);
			$c->add(J002tUsuarioPeer::CO_USUARIO, $this->co_usuario_updated);
			$this->aJ002tUsuarioRelatedByCoUsuarioUpdated = J002tUsuarioPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aJ002tUsuarioRelatedByCoUsuarioUpdated->addJ047tDocumentoNormativosRelatedByCoUsuarioUpdated($this);
			 */
		}
		return $this->aJ002tUsuarioRelatedByCoUsuarioUpdated;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aJ049tTipoMarco = null;
			$this->aJ048tEstadoDocumento = null;
			$this->aJ002tUsuarioRelatedByCoAprueba1 = null;
			$this->aJ002tUsuarioRelatedByCoAprueba2 = null;
			$this->aJ002tUsuarioRelatedByCoElimina1 = null;
			$this->aJ002tUsuarioRelatedByCoElimina2 = null;
			$this->aJ002tUsuarioRelatedByCoUsuarioCreated = null;
			$this->aJ002tUsuarioRelatedByCoUsuarioUpdated = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseJ047tDocumentoNormativo:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseJ047tDocumentoNormativo::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseJ047tDocumentoNormativo
