<?php

/**
 * Base class that represents a row from the 'j019t_participantes' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Nov  9 14:57:52 2015
 *
 * @package    lib.model.om
 */
abstract class BaseJ019tParticipantes extends BaseObject  implements Persistent {


  const PEER = 'J019tParticipantesPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        J019tParticipantesPeer
	 */
	protected static $peer;

	/**
	 * The value for the co_participante field.
	 * @var        string
	 */
	protected $co_participante;

	/**
	 * The value for the co_usuario_elabora field.
	 * @var        string
	 */
	protected $co_usuario_elabora;

	/**
	 * The value for the co_forense field.
	 * @var        string
	 */
	protected $co_forense;

	/**
	 * The value for the co_informe_recomendaciones field.
	 * @var        string
	 */
	protected $co_informe_recomendaciones;

	/**
	 * The value for the co_informe_incidente field.
	 * @var        string
	 */
	protected $co_informe_incidente;

	/**
	 * The value for the co_informe_forense field.
	 * @var        string
	 */
	protected $co_informe_forense;

	/**
	 * The value for the co_informe_depuracion field.
	 * @var        string
	 */
	protected $co_informe_depuracion;

	/**
	 * The value for the co_mantenimiento field.
	 * @var        string
	 */
	protected $co_mantenimiento;

	/**
	 * The value for the co_doumento_normativo field.
	 * @var        string
	 */
	protected $co_doumento_normativo;

	/**
	 * @var        J002tUsuario
	 */
	protected $aJ002tUsuario;

	/**
	 * @var        J016tForense
	 */
	protected $aJ016tForense;

	/**
	 * @var        J018tInformeForense
	 */
	protected $aJ018tInformeForense;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseJ019tParticipantes object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [co_participante] column value.
	 * 
	 * @return     string
	 */
	public function getCoParticipante()
	{
		return $this->co_participante;
	}

	/**
	 * Get the [co_usuario_elabora] column value.
	 * 
	 * @return     string
	 */
	public function getCoUsuarioElabora()
	{
		return $this->co_usuario_elabora;
	}

	/**
	 * Get the [co_forense] column value.
	 * 
	 * @return     string
	 */
	public function getCoForense()
	{
		return $this->co_forense;
	}

	/**
	 * Get the [co_informe_recomendaciones] column value.
	 * 
	 * @return     string
	 */
	public function getCoInformeRecomendaciones()
	{
		return $this->co_informe_recomendaciones;
	}

	/**
	 * Get the [co_informe_incidente] column value.
	 * 
	 * @return     string
	 */
	public function getCoInformeIncidente()
	{
		return $this->co_informe_incidente;
	}

	/**
	 * Get the [co_informe_forense] column value.
	 * 
	 * @return     string
	 */
	public function getCoInformeForense()
	{
		return $this->co_informe_forense;
	}

	/**
	 * Get the [co_informe_depuracion] column value.
	 * 
	 * @return     string
	 */
	public function getCoInformeDepuracion()
	{
		return $this->co_informe_depuracion;
	}

	/**
	 * Get the [co_mantenimiento] column value.
	 * 
	 * @return     string
	 */
	public function getCoMantenimiento()
	{
		return $this->co_mantenimiento;
	}

	/**
	 * Get the [co_doumento_normativo] column value.
	 * 
	 * @return     string
	 */
	public function getCoDoumentoNormativo()
	{
		return $this->co_doumento_normativo;
	}

	/**
	 * Set the value of [co_participante] column.
	 * 
	 * @param      string $v new value
	 * @return     J019tParticipantes The current object (for fluent API support)
	 */
	public function setCoParticipante($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_participante !== $v) {
			$this->co_participante = $v;
			$this->modifiedColumns[] = J019tParticipantesPeer::CO_PARTICIPANTE;
		}

		return $this;
	} // setCoParticipante()

	/**
	 * Set the value of [co_usuario_elabora] column.
	 * 
	 * @param      string $v new value
	 * @return     J019tParticipantes The current object (for fluent API support)
	 */
	public function setCoUsuarioElabora($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_usuario_elabora !== $v) {
			$this->co_usuario_elabora = $v;
			$this->modifiedColumns[] = J019tParticipantesPeer::CO_USUARIO_ELABORA;
		}

		if ($this->aJ002tUsuario !== null && $this->aJ002tUsuario->getCoUsuario() !== $v) {
			$this->aJ002tUsuario = null;
		}

		return $this;
	} // setCoUsuarioElabora()

	/**
	 * Set the value of [co_forense] column.
	 * 
	 * @param      string $v new value
	 * @return     J019tParticipantes The current object (for fluent API support)
	 */
	public function setCoForense($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_forense !== $v) {
			$this->co_forense = $v;
			$this->modifiedColumns[] = J019tParticipantesPeer::CO_FORENSE;
		}

		if ($this->aJ016tForense !== null && $this->aJ016tForense->getCoForense() !== $v) {
			$this->aJ016tForense = null;
		}

		return $this;
	} // setCoForense()

	/**
	 * Set the value of [co_informe_recomendaciones] column.
	 * 
	 * @param      string $v new value
	 * @return     J019tParticipantes The current object (for fluent API support)
	 */
	public function setCoInformeRecomendaciones($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_informe_recomendaciones !== $v) {
			$this->co_informe_recomendaciones = $v;
			$this->modifiedColumns[] = J019tParticipantesPeer::CO_INFORME_RECOMENDACIONES;
		}

		return $this;
	} // setCoInformeRecomendaciones()

	/**
	 * Set the value of [co_informe_incidente] column.
	 * 
	 * @param      string $v new value
	 * @return     J019tParticipantes The current object (for fluent API support)
	 */
	public function setCoInformeIncidente($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_informe_incidente !== $v) {
			$this->co_informe_incidente = $v;
			$this->modifiedColumns[] = J019tParticipantesPeer::CO_INFORME_INCIDENTE;
		}

		return $this;
	} // setCoInformeIncidente()

	/**
	 * Set the value of [co_informe_forense] column.
	 * 
	 * @param      string $v new value
	 * @return     J019tParticipantes The current object (for fluent API support)
	 */
	public function setCoInformeForense($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_informe_forense !== $v) {
			$this->co_informe_forense = $v;
			$this->modifiedColumns[] = J019tParticipantesPeer::CO_INFORME_FORENSE;
		}

		if ($this->aJ018tInformeForense !== null && $this->aJ018tInformeForense->getCoInformeForense() !== $v) {
			$this->aJ018tInformeForense = null;
		}

		return $this;
	} // setCoInformeForense()

	/**
	 * Set the value of [co_informe_depuracion] column.
	 * 
	 * @param      string $v new value
	 * @return     J019tParticipantes The current object (for fluent API support)
	 */
	public function setCoInformeDepuracion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_informe_depuracion !== $v) {
			$this->co_informe_depuracion = $v;
			$this->modifiedColumns[] = J019tParticipantesPeer::CO_INFORME_DEPURACION;
		}

		return $this;
	} // setCoInformeDepuracion()

	/**
	 * Set the value of [co_mantenimiento] column.
	 * 
	 * @param      string $v new value
	 * @return     J019tParticipantes The current object (for fluent API support)
	 */
	public function setCoMantenimiento($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_mantenimiento !== $v) {
			$this->co_mantenimiento = $v;
			$this->modifiedColumns[] = J019tParticipantesPeer::CO_MANTENIMIENTO;
		}

		return $this;
	} // setCoMantenimiento()

	/**
	 * Set the value of [co_doumento_normativo] column.
	 * 
	 * @param      string $v new value
	 * @return     J019tParticipantes The current object (for fluent API support)
	 */
	public function setCoDoumentoNormativo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_doumento_normativo !== $v) {
			$this->co_doumento_normativo = $v;
			$this->modifiedColumns[] = J019tParticipantesPeer::CO_DOUMENTO_NORMATIVO;
		}

		return $this;
	} // setCoDoumentoNormativo()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->co_participante = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
			$this->co_usuario_elabora = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->co_forense = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->co_informe_recomendaciones = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->co_informe_incidente = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->co_informe_forense = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->co_informe_depuracion = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->co_mantenimiento = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->co_doumento_normativo = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 9; // 9 = J019tParticipantesPeer::NUM_COLUMNS - J019tParticipantesPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating J019tParticipantes object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aJ002tUsuario !== null && $this->co_usuario_elabora !== $this->aJ002tUsuario->getCoUsuario()) {
			$this->aJ002tUsuario = null;
		}
		if ($this->aJ016tForense !== null && $this->co_forense !== $this->aJ016tForense->getCoForense()) {
			$this->aJ016tForense = null;
		}
		if ($this->aJ018tInformeForense !== null && $this->co_informe_forense !== $this->aJ018tInformeForense->getCoInformeForense()) {
			$this->aJ018tInformeForense = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(J019tParticipantesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = J019tParticipantesPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aJ002tUsuario = null;
			$this->aJ016tForense = null;
			$this->aJ018tInformeForense = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseJ019tParticipantes:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(J019tParticipantesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			J019tParticipantesPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseJ019tParticipantes:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseJ019tParticipantes:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(J019tParticipantesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseJ019tParticipantes:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			J019tParticipantesPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aJ002tUsuario !== null) {
				if ($this->aJ002tUsuario->isModified() || $this->aJ002tUsuario->isNew()) {
					$affectedRows += $this->aJ002tUsuario->save($con);
				}
				$this->setJ002tUsuario($this->aJ002tUsuario);
			}

			if ($this->aJ016tForense !== null) {
				if ($this->aJ016tForense->isModified() || $this->aJ016tForense->isNew()) {
					$affectedRows += $this->aJ016tForense->save($con);
				}
				$this->setJ016tForense($this->aJ016tForense);
			}

			if ($this->aJ018tInformeForense !== null) {
				if ($this->aJ018tInformeForense->isModified() || $this->aJ018tInformeForense->isNew()) {
					$affectedRows += $this->aJ018tInformeForense->save($con);
				}
				$this->setJ018tInformeForense($this->aJ018tInformeForense);
			}


			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = J019tParticipantesPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setNew(false);
				} else {
					$affectedRows += J019tParticipantesPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aJ002tUsuario !== null) {
				if (!$this->aJ002tUsuario->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aJ002tUsuario->getValidationFailures());
				}
			}

			if ($this->aJ016tForense !== null) {
				if (!$this->aJ016tForense->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aJ016tForense->getValidationFailures());
				}
			}

			if ($this->aJ018tInformeForense !== null) {
				if (!$this->aJ018tInformeForense->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aJ018tInformeForense->getValidationFailures());
				}
			}


			if (($retval = J019tParticipantesPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = J019tParticipantesPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getCoParticipante();
				break;
			case 1:
				return $this->getCoUsuarioElabora();
				break;
			case 2:
				return $this->getCoForense();
				break;
			case 3:
				return $this->getCoInformeRecomendaciones();
				break;
			case 4:
				return $this->getCoInformeIncidente();
				break;
			case 5:
				return $this->getCoInformeForense();
				break;
			case 6:
				return $this->getCoInformeDepuracion();
				break;
			case 7:
				return $this->getCoMantenimiento();
				break;
			case 8:
				return $this->getCoDoumentoNormativo();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = J019tParticipantesPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getCoParticipante(),
			$keys[1] => $this->getCoUsuarioElabora(),
			$keys[2] => $this->getCoForense(),
			$keys[3] => $this->getCoInformeRecomendaciones(),
			$keys[4] => $this->getCoInformeIncidente(),
			$keys[5] => $this->getCoInformeForense(),
			$keys[6] => $this->getCoInformeDepuracion(),
			$keys[7] => $this->getCoMantenimiento(),
			$keys[8] => $this->getCoDoumentoNormativo(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = J019tParticipantesPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setCoParticipante($value);
				break;
			case 1:
				$this->setCoUsuarioElabora($value);
				break;
			case 2:
				$this->setCoForense($value);
				break;
			case 3:
				$this->setCoInformeRecomendaciones($value);
				break;
			case 4:
				$this->setCoInformeIncidente($value);
				break;
			case 5:
				$this->setCoInformeForense($value);
				break;
			case 6:
				$this->setCoInformeDepuracion($value);
				break;
			case 7:
				$this->setCoMantenimiento($value);
				break;
			case 8:
				$this->setCoDoumentoNormativo($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = J019tParticipantesPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setCoParticipante($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setCoUsuarioElabora($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setCoForense($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setCoInformeRecomendaciones($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setCoInformeIncidente($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setCoInformeForense($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setCoInformeDepuracion($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setCoMantenimiento($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setCoDoumentoNormativo($arr[$keys[8]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(J019tParticipantesPeer::DATABASE_NAME);

		if ($this->isColumnModified(J019tParticipantesPeer::CO_PARTICIPANTE)) $criteria->add(J019tParticipantesPeer::CO_PARTICIPANTE, $this->co_participante);
		if ($this->isColumnModified(J019tParticipantesPeer::CO_USUARIO_ELABORA)) $criteria->add(J019tParticipantesPeer::CO_USUARIO_ELABORA, $this->co_usuario_elabora);
		if ($this->isColumnModified(J019tParticipantesPeer::CO_FORENSE)) $criteria->add(J019tParticipantesPeer::CO_FORENSE, $this->co_forense);
		if ($this->isColumnModified(J019tParticipantesPeer::CO_INFORME_RECOMENDACIONES)) $criteria->add(J019tParticipantesPeer::CO_INFORME_RECOMENDACIONES, $this->co_informe_recomendaciones);
		if ($this->isColumnModified(J019tParticipantesPeer::CO_INFORME_INCIDENTE)) $criteria->add(J019tParticipantesPeer::CO_INFORME_INCIDENTE, $this->co_informe_incidente);
		if ($this->isColumnModified(J019tParticipantesPeer::CO_INFORME_FORENSE)) $criteria->add(J019tParticipantesPeer::CO_INFORME_FORENSE, $this->co_informe_forense);
		if ($this->isColumnModified(J019tParticipantesPeer::CO_INFORME_DEPURACION)) $criteria->add(J019tParticipantesPeer::CO_INFORME_DEPURACION, $this->co_informe_depuracion);
		if ($this->isColumnModified(J019tParticipantesPeer::CO_MANTENIMIENTO)) $criteria->add(J019tParticipantesPeer::CO_MANTENIMIENTO, $this->co_mantenimiento);
		if ($this->isColumnModified(J019tParticipantesPeer::CO_DOUMENTO_NORMATIVO)) $criteria->add(J019tParticipantesPeer::CO_DOUMENTO_NORMATIVO, $this->co_doumento_normativo);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(J019tParticipantesPeer::DATABASE_NAME);

		$criteria->add(J019tParticipantesPeer::CO_PARTICIPANTE, $this->co_participante);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     string
	 */
	public function getPrimaryKey()
	{
		return $this->getCoParticipante();
	}

	/**
	 * Generic method to set the primary key (co_participante column).
	 *
	 * @param      string $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setCoParticipante($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of J019tParticipantes (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setCoParticipante($this->co_participante);

		$copyObj->setCoUsuarioElabora($this->co_usuario_elabora);

		$copyObj->setCoForense($this->co_forense);

		$copyObj->setCoInformeRecomendaciones($this->co_informe_recomendaciones);

		$copyObj->setCoInformeIncidente($this->co_informe_incidente);

		$copyObj->setCoInformeForense($this->co_informe_forense);

		$copyObj->setCoInformeDepuracion($this->co_informe_depuracion);

		$copyObj->setCoMantenimiento($this->co_mantenimiento);

		$copyObj->setCoDoumentoNormativo($this->co_doumento_normativo);


		$copyObj->setNew(true);

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     J019tParticipantes Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     J019tParticipantesPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new J019tParticipantesPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a J002tUsuario object.
	 *
	 * @param      J002tUsuario $v
	 * @return     J019tParticipantes The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setJ002tUsuario(J002tUsuario $v = null)
	{
		if ($v === null) {
			$this->setCoUsuarioElabora(NULL);
		} else {
			$this->setCoUsuarioElabora($v->getCoUsuario());
		}

		$this->aJ002tUsuario = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the J002tUsuario object, it will not be re-added.
		if ($v !== null) {
			$v->addJ019tParticipantes($this);
		}

		return $this;
	}


	/**
	 * Get the associated J002tUsuario object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     J002tUsuario The associated J002tUsuario object.
	 * @throws     PropelException
	 */
	public function getJ002tUsuario(PropelPDO $con = null)
	{
		if ($this->aJ002tUsuario === null && (($this->co_usuario_elabora !== "" && $this->co_usuario_elabora !== null))) {
			$c = new Criteria(J002tUsuarioPeer::DATABASE_NAME);
			$c->add(J002tUsuarioPeer::CO_USUARIO, $this->co_usuario_elabora);
			$this->aJ002tUsuario = J002tUsuarioPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aJ002tUsuario->addJ019tParticipantess($this);
			 */
		}
		return $this->aJ002tUsuario;
	}

	/**
	 * Declares an association between this object and a J016tForense object.
	 *
	 * @param      J016tForense $v
	 * @return     J019tParticipantes The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setJ016tForense(J016tForense $v = null)
	{
		if ($v === null) {
			$this->setCoForense(NULL);
		} else {
			$this->setCoForense($v->getCoForense());
		}

		$this->aJ016tForense = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the J016tForense object, it will not be re-added.
		if ($v !== null) {
			$v->addJ019tParticipantes($this);
		}

		return $this;
	}


	/**
	 * Get the associated J016tForense object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     J016tForense The associated J016tForense object.
	 * @throws     PropelException
	 */
	public function getJ016tForense(PropelPDO $con = null)
	{
		if ($this->aJ016tForense === null && (($this->co_forense !== "" && $this->co_forense !== null))) {
			$c = new Criteria(J016tForensePeer::DATABASE_NAME);
			$c->add(J016tForensePeer::CO_FORENSE, $this->co_forense);
			$this->aJ016tForense = J016tForensePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aJ016tForense->addJ019tParticipantess($this);
			 */
		}
		return $this->aJ016tForense;
	}

	/**
	 * Declares an association between this object and a J018tInformeForense object.
	 *
	 * @param      J018tInformeForense $v
	 * @return     J019tParticipantes The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setJ018tInformeForense(J018tInformeForense $v = null)
	{
		if ($v === null) {
			$this->setCoInformeForense(NULL);
		} else {
			$this->setCoInformeForense($v->getCoInformeForense());
		}

		$this->aJ018tInformeForense = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the J018tInformeForense object, it will not be re-added.
		if ($v !== null) {
			$v->addJ019tParticipantes($this);
		}

		return $this;
	}


	/**
	 * Get the associated J018tInformeForense object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     J018tInformeForense The associated J018tInformeForense object.
	 * @throws     PropelException
	 */
	public function getJ018tInformeForense(PropelPDO $con = null)
	{
		if ($this->aJ018tInformeForense === null && (($this->co_informe_forense !== "" && $this->co_informe_forense !== null))) {
			$c = new Criteria(J018tInformeForensePeer::DATABASE_NAME);
			$c->add(J018tInformeForensePeer::CO_INFORME_FORENSE, $this->co_informe_forense);
			$this->aJ018tInformeForense = J018tInformeForensePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aJ018tInformeForense->addJ019tParticipantess($this);
			 */
		}
		return $this->aJ018tInformeForense;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aJ002tUsuario = null;
			$this->aJ016tForense = null;
			$this->aJ018tInformeForense = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseJ019tParticipantes:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseJ019tParticipantes::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseJ019tParticipantes
