<?php

/**
 * Base static class for performing query and update operations on the 'j002t_usuario' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Wed Nov 11 13:50:03 2015
 *
 * @package    lib.model.om
 */
abstract class BaseJ002tUsuarioPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'j002t_usuario';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.J002tUsuario';

	/** The total number of columns. */
	const NUM_COLUMNS = 8;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the CO_USUARIO field */
	const CO_USUARIO = 'j002t_usuario.CO_USUARIO';

	/** the column name for the TX_INDICADOR field */
	const TX_INDICADOR = 'j002t_usuario.TX_INDICADOR';

	/** the column name for the NB_EMPLEADO field */
	const NB_EMPLEADO = 'j002t_usuario.NB_EMPLEADO';

	/** the column name for the AP_EMPLEADO field */
	const AP_EMPLEADO = 'j002t_usuario.AP_EMPLEADO';

	/** the column name for the CO_DIVISION field */
	const CO_DIVISION = 'j002t_usuario.CO_DIVISION';

	/** the column name for the CO_ROL field */
	const CO_ROL = 'j002t_usuario.CO_ROL';

	/** the column name for the CO_REGION field */
	const CO_REGION = 'j002t_usuario.CO_REGION';

	/** the column name for the CO_NEGOCIO field */
	const CO_NEGOCIO = 'j002t_usuario.CO_NEGOCIO';

	/**
	 * An identiy map to hold any loaded instances of J002tUsuario objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array J002tUsuario[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('CoUsuario', 'TxIndicador', 'NbEmpleado', 'ApEmpleado', 'CoDivision', 'CoRol', 'CoRegion', 'CoNegocio', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('coUsuario', 'txIndicador', 'nbEmpleado', 'apEmpleado', 'coDivision', 'coRol', 'coRegion', 'coNegocio', ),
		BasePeer::TYPE_COLNAME => array (self::CO_USUARIO, self::TX_INDICADOR, self::NB_EMPLEADO, self::AP_EMPLEADO, self::CO_DIVISION, self::CO_ROL, self::CO_REGION, self::CO_NEGOCIO, ),
		BasePeer::TYPE_FIELDNAME => array ('co_usuario', 'tx_indicador', 'nb_empleado', 'ap_empleado', 'co_division', 'co_rol', 'co_region', 'co_negocio', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('CoUsuario' => 0, 'TxIndicador' => 1, 'NbEmpleado' => 2, 'ApEmpleado' => 3, 'CoDivision' => 4, 'CoRol' => 5, 'CoRegion' => 6, 'CoNegocio' => 7, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('coUsuario' => 0, 'txIndicador' => 1, 'nbEmpleado' => 2, 'apEmpleado' => 3, 'coDivision' => 4, 'coRol' => 5, 'coRegion' => 6, 'coNegocio' => 7, ),
		BasePeer::TYPE_COLNAME => array (self::CO_USUARIO => 0, self::TX_INDICADOR => 1, self::NB_EMPLEADO => 2, self::AP_EMPLEADO => 3, self::CO_DIVISION => 4, self::CO_ROL => 5, self::CO_REGION => 6, self::CO_NEGOCIO => 7, ),
		BasePeer::TYPE_FIELDNAME => array ('co_usuario' => 0, 'tx_indicador' => 1, 'nb_empleado' => 2, 'ap_empleado' => 3, 'co_division' => 4, 'co_rol' => 5, 'co_region' => 6, 'co_negocio' => 7, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new J002tUsuarioMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. J002tUsuarioPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(J002tUsuarioPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(J002tUsuarioPeer::CO_USUARIO);

		$criteria->addSelectColumn(J002tUsuarioPeer::TX_INDICADOR);

		$criteria->addSelectColumn(J002tUsuarioPeer::NB_EMPLEADO);

		$criteria->addSelectColumn(J002tUsuarioPeer::AP_EMPLEADO);

		$criteria->addSelectColumn(J002tUsuarioPeer::CO_DIVISION);

		$criteria->addSelectColumn(J002tUsuarioPeer::CO_ROL);

		$criteria->addSelectColumn(J002tUsuarioPeer::CO_REGION);

		$criteria->addSelectColumn(J002tUsuarioPeer::CO_NEGOCIO);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(J002tUsuarioPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			J002tUsuarioPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(J002tUsuarioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseJ002tUsuarioPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseJ002tUsuarioPeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     J002tUsuario
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = J002tUsuarioPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return J002tUsuarioPeer::populateObjects(J002tUsuarioPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseJ002tUsuarioPeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseJ002tUsuarioPeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(J002tUsuarioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			J002tUsuarioPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      J002tUsuario $value A J002tUsuario object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(J002tUsuario $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getCoUsuario();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A J002tUsuario object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof J002tUsuario) {
				$key = (string) $value->getCoUsuario();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or J002tUsuario object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     J002tUsuario Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 0] === null) {
			return null;
		}
		return (string) $row[$startcol + 0];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = J002tUsuarioPeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = J002tUsuarioPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = J002tUsuarioPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				J002tUsuarioPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the number of rows matching criteria, joining the related J008tDivision table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinJ008tDivision(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(J002tUsuarioPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			J002tUsuarioPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(J002tUsuarioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(J002tUsuarioPeer::CO_DIVISION,), array(J008tDivisionPeer::CO_DIVISION,), $join_behavior);


    foreach (sfMixer::getCallables('BaseJ002tUsuarioPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseJ002tUsuarioPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related J003tRol table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinJ003tRol(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(J002tUsuarioPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			J002tUsuarioPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(J002tUsuarioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(J002tUsuarioPeer::CO_ROL,), array(J003tRolPeer::CO_ROL,), $join_behavior);


    foreach (sfMixer::getCallables('BaseJ002tUsuarioPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseJ002tUsuarioPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related J007tRegion table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinJ007tRegion(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(J002tUsuarioPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			J002tUsuarioPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(J002tUsuarioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(J002tUsuarioPeer::CO_REGION,), array(J007tRegionPeer::CO_REGION,), $join_behavior);


    foreach (sfMixer::getCallables('BaseJ002tUsuarioPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseJ002tUsuarioPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related J014tNegocio table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinJ014tNegocio(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(J002tUsuarioPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			J002tUsuarioPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(J002tUsuarioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(J002tUsuarioPeer::CO_NEGOCIO,), array(J014tNegocioPeer::CO_NEGOCIO,), $join_behavior);


    foreach (sfMixer::getCallables('BaseJ002tUsuarioPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseJ002tUsuarioPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of J002tUsuario objects pre-filled with their J008tDivision objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of J002tUsuario objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinJ008tDivision(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseJ002tUsuarioPeer:doSelectJoin:doSelectJoin') as $callable)
    {
      call_user_func($callable, 'BaseJ002tUsuarioPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		J002tUsuarioPeer::addSelectColumns($c);
		$startcol = (J002tUsuarioPeer::NUM_COLUMNS - J002tUsuarioPeer::NUM_LAZY_LOAD_COLUMNS);
		J008tDivisionPeer::addSelectColumns($c);

		$c->addJoin(array(J002tUsuarioPeer::CO_DIVISION,), array(J008tDivisionPeer::CO_DIVISION,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = J002tUsuarioPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = J002tUsuarioPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = J002tUsuarioPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				J002tUsuarioPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = J008tDivisionPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = J008tDivisionPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = J008tDivisionPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					J008tDivisionPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (J002tUsuario) to $obj2 (J008tDivision)
				$obj2->addJ002tUsuario($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of J002tUsuario objects pre-filled with their J003tRol objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of J002tUsuario objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinJ003tRol(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		J002tUsuarioPeer::addSelectColumns($c);
		$startcol = (J002tUsuarioPeer::NUM_COLUMNS - J002tUsuarioPeer::NUM_LAZY_LOAD_COLUMNS);
		J003tRolPeer::addSelectColumns($c);

		$c->addJoin(array(J002tUsuarioPeer::CO_ROL,), array(J003tRolPeer::CO_ROL,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = J002tUsuarioPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = J002tUsuarioPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = J002tUsuarioPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				J002tUsuarioPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = J003tRolPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = J003tRolPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = J003tRolPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					J003tRolPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (J002tUsuario) to $obj2 (J003tRol)
				$obj2->addJ002tUsuario($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of J002tUsuario objects pre-filled with their J007tRegion objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of J002tUsuario objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinJ007tRegion(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		J002tUsuarioPeer::addSelectColumns($c);
		$startcol = (J002tUsuarioPeer::NUM_COLUMNS - J002tUsuarioPeer::NUM_LAZY_LOAD_COLUMNS);
		J007tRegionPeer::addSelectColumns($c);

		$c->addJoin(array(J002tUsuarioPeer::CO_REGION,), array(J007tRegionPeer::CO_REGION,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = J002tUsuarioPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = J002tUsuarioPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = J002tUsuarioPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				J002tUsuarioPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = J007tRegionPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = J007tRegionPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = J007tRegionPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					J007tRegionPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (J002tUsuario) to $obj2 (J007tRegion)
				$obj2->addJ002tUsuario($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of J002tUsuario objects pre-filled with their J014tNegocio objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of J002tUsuario objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinJ014tNegocio(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		J002tUsuarioPeer::addSelectColumns($c);
		$startcol = (J002tUsuarioPeer::NUM_COLUMNS - J002tUsuarioPeer::NUM_LAZY_LOAD_COLUMNS);
		J014tNegocioPeer::addSelectColumns($c);

		$c->addJoin(array(J002tUsuarioPeer::CO_NEGOCIO,), array(J014tNegocioPeer::CO_NEGOCIO,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = J002tUsuarioPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = J002tUsuarioPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = J002tUsuarioPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				J002tUsuarioPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = J014tNegocioPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = J014tNegocioPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = J014tNegocioPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					J014tNegocioPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (J002tUsuario) to $obj2 (J014tNegocio)
				$obj2->addJ002tUsuario($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining all related tables
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(J002tUsuarioPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			J002tUsuarioPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(J002tUsuarioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(J002tUsuarioPeer::CO_DIVISION,), array(J008tDivisionPeer::CO_DIVISION,), $join_behavior);
		$criteria->addJoin(array(J002tUsuarioPeer::CO_ROL,), array(J003tRolPeer::CO_ROL,), $join_behavior);
		$criteria->addJoin(array(J002tUsuarioPeer::CO_REGION,), array(J007tRegionPeer::CO_REGION,), $join_behavior);
		$criteria->addJoin(array(J002tUsuarioPeer::CO_NEGOCIO,), array(J014tNegocioPeer::CO_NEGOCIO,), $join_behavior);

    foreach (sfMixer::getCallables('BaseJ002tUsuarioPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseJ002tUsuarioPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}

	/**
	 * Selects a collection of J002tUsuario objects pre-filled with all related objects.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of J002tUsuario objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAll(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseJ002tUsuarioPeer:doSelectJoinAll:doSelectJoinAll') as $callable)
    {
      call_user_func($callable, 'BaseJ002tUsuarioPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		J002tUsuarioPeer::addSelectColumns($c);
		$startcol2 = (J002tUsuarioPeer::NUM_COLUMNS - J002tUsuarioPeer::NUM_LAZY_LOAD_COLUMNS);

		J008tDivisionPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (J008tDivisionPeer::NUM_COLUMNS - J008tDivisionPeer::NUM_LAZY_LOAD_COLUMNS);

		J003tRolPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (J003tRolPeer::NUM_COLUMNS - J003tRolPeer::NUM_LAZY_LOAD_COLUMNS);

		J007tRegionPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (J007tRegionPeer::NUM_COLUMNS - J007tRegionPeer::NUM_LAZY_LOAD_COLUMNS);

		J014tNegocioPeer::addSelectColumns($c);
		$startcol6 = $startcol5 + (J014tNegocioPeer::NUM_COLUMNS - J014tNegocioPeer::NUM_LAZY_LOAD_COLUMNS);

		$c->addJoin(array(J002tUsuarioPeer::CO_DIVISION,), array(J008tDivisionPeer::CO_DIVISION,), $join_behavior);
		$c->addJoin(array(J002tUsuarioPeer::CO_ROL,), array(J003tRolPeer::CO_ROL,), $join_behavior);
		$c->addJoin(array(J002tUsuarioPeer::CO_REGION,), array(J007tRegionPeer::CO_REGION,), $join_behavior);
		$c->addJoin(array(J002tUsuarioPeer::CO_NEGOCIO,), array(J014tNegocioPeer::CO_NEGOCIO,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = J002tUsuarioPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = J002tUsuarioPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = J002tUsuarioPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				J002tUsuarioPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

			// Add objects for joined J008tDivision rows

			$key2 = J008tDivisionPeer::getPrimaryKeyHashFromRow($row, $startcol2);
			if ($key2 !== null) {
				$obj2 = J008tDivisionPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = J008tDivisionPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					J008tDivisionPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 loaded

				// Add the $obj1 (J002tUsuario) to the collection in $obj2 (J008tDivision)
				$obj2->addJ002tUsuario($obj1);
			} // if joined row not null

			// Add objects for joined J003tRol rows

			$key3 = J003tRolPeer::getPrimaryKeyHashFromRow($row, $startcol3);
			if ($key3 !== null) {
				$obj3 = J003tRolPeer::getInstanceFromPool($key3);
				if (!$obj3) {

					$omClass = J003tRolPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					J003tRolPeer::addInstanceToPool($obj3, $key3);
				} // if obj3 loaded

				// Add the $obj1 (J002tUsuario) to the collection in $obj3 (J003tRol)
				$obj3->addJ002tUsuario($obj1);
			} // if joined row not null

			// Add objects for joined J007tRegion rows

			$key4 = J007tRegionPeer::getPrimaryKeyHashFromRow($row, $startcol4);
			if ($key4 !== null) {
				$obj4 = J007tRegionPeer::getInstanceFromPool($key4);
				if (!$obj4) {

					$omClass = J007tRegionPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					J007tRegionPeer::addInstanceToPool($obj4, $key4);
				} // if obj4 loaded

				// Add the $obj1 (J002tUsuario) to the collection in $obj4 (J007tRegion)
				$obj4->addJ002tUsuario($obj1);
			} // if joined row not null

			// Add objects for joined J014tNegocio rows

			$key5 = J014tNegocioPeer::getPrimaryKeyHashFromRow($row, $startcol5);
			if ($key5 !== null) {
				$obj5 = J014tNegocioPeer::getInstanceFromPool($key5);
				if (!$obj5) {

					$omClass = J014tNegocioPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					J014tNegocioPeer::addInstanceToPool($obj5, $key5);
				} // if obj5 loaded

				// Add the $obj1 (J002tUsuario) to the collection in $obj5 (J014tNegocio)
				$obj5->addJ002tUsuario($obj1);
			} // if joined row not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related J008tDivision table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptJ008tDivision(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			J002tUsuarioPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(J002tUsuarioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(J002tUsuarioPeer::CO_ROL,), array(J003tRolPeer::CO_ROL,), $join_behavior);
				$criteria->addJoin(array(J002tUsuarioPeer::CO_REGION,), array(J007tRegionPeer::CO_REGION,), $join_behavior);
				$criteria->addJoin(array(J002tUsuarioPeer::CO_NEGOCIO,), array(J014tNegocioPeer::CO_NEGOCIO,), $join_behavior);

    foreach (sfMixer::getCallables('BaseJ002tUsuarioPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseJ002tUsuarioPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related J003tRol table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptJ003tRol(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			J002tUsuarioPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(J002tUsuarioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(J002tUsuarioPeer::CO_DIVISION,), array(J008tDivisionPeer::CO_DIVISION,), $join_behavior);
				$criteria->addJoin(array(J002tUsuarioPeer::CO_REGION,), array(J007tRegionPeer::CO_REGION,), $join_behavior);
				$criteria->addJoin(array(J002tUsuarioPeer::CO_NEGOCIO,), array(J014tNegocioPeer::CO_NEGOCIO,), $join_behavior);

    foreach (sfMixer::getCallables('BaseJ002tUsuarioPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseJ002tUsuarioPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related J007tRegion table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptJ007tRegion(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			J002tUsuarioPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(J002tUsuarioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(J002tUsuarioPeer::CO_DIVISION,), array(J008tDivisionPeer::CO_DIVISION,), $join_behavior);
				$criteria->addJoin(array(J002tUsuarioPeer::CO_ROL,), array(J003tRolPeer::CO_ROL,), $join_behavior);
				$criteria->addJoin(array(J002tUsuarioPeer::CO_NEGOCIO,), array(J014tNegocioPeer::CO_NEGOCIO,), $join_behavior);

    foreach (sfMixer::getCallables('BaseJ002tUsuarioPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseJ002tUsuarioPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related J014tNegocio table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptJ014tNegocio(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			J002tUsuarioPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(J002tUsuarioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(J002tUsuarioPeer::CO_DIVISION,), array(J008tDivisionPeer::CO_DIVISION,), $join_behavior);
				$criteria->addJoin(array(J002tUsuarioPeer::CO_ROL,), array(J003tRolPeer::CO_ROL,), $join_behavior);
				$criteria->addJoin(array(J002tUsuarioPeer::CO_REGION,), array(J007tRegionPeer::CO_REGION,), $join_behavior);

    foreach (sfMixer::getCallables('BaseJ002tUsuarioPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseJ002tUsuarioPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of J002tUsuario objects pre-filled with all related objects except J008tDivision.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of J002tUsuario objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptJ008tDivision(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseJ002tUsuarioPeer:doSelectJoinAllExcept:doSelectJoinAllExcept') as $callable)
    {
      call_user_func($callable, 'BaseJ002tUsuarioPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		J002tUsuarioPeer::addSelectColumns($c);
		$startcol2 = (J002tUsuarioPeer::NUM_COLUMNS - J002tUsuarioPeer::NUM_LAZY_LOAD_COLUMNS);

		J003tRolPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (J003tRolPeer::NUM_COLUMNS - J003tRolPeer::NUM_LAZY_LOAD_COLUMNS);

		J007tRegionPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (J007tRegionPeer::NUM_COLUMNS - J007tRegionPeer::NUM_LAZY_LOAD_COLUMNS);

		J014tNegocioPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (J014tNegocioPeer::NUM_COLUMNS - J014tNegocioPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(J002tUsuarioPeer::CO_ROL,), array(J003tRolPeer::CO_ROL,), $join_behavior);
				$c->addJoin(array(J002tUsuarioPeer::CO_REGION,), array(J007tRegionPeer::CO_REGION,), $join_behavior);
				$c->addJoin(array(J002tUsuarioPeer::CO_NEGOCIO,), array(J014tNegocioPeer::CO_NEGOCIO,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = J002tUsuarioPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = J002tUsuarioPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = J002tUsuarioPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				J002tUsuarioPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined J003tRol rows

				$key2 = J003tRolPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = J003tRolPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = J003tRolPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					J003tRolPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (J002tUsuario) to the collection in $obj2 (J003tRol)
				$obj2->addJ002tUsuario($obj1);

			} // if joined row is not null

				// Add objects for joined J007tRegion rows

				$key3 = J007tRegionPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = J007tRegionPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = J007tRegionPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					J007tRegionPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (J002tUsuario) to the collection in $obj3 (J007tRegion)
				$obj3->addJ002tUsuario($obj1);

			} // if joined row is not null

				// Add objects for joined J014tNegocio rows

				$key4 = J014tNegocioPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = J014tNegocioPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = J014tNegocioPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					J014tNegocioPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (J002tUsuario) to the collection in $obj4 (J014tNegocio)
				$obj4->addJ002tUsuario($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of J002tUsuario objects pre-filled with all related objects except J003tRol.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of J002tUsuario objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptJ003tRol(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		J002tUsuarioPeer::addSelectColumns($c);
		$startcol2 = (J002tUsuarioPeer::NUM_COLUMNS - J002tUsuarioPeer::NUM_LAZY_LOAD_COLUMNS);

		J008tDivisionPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (J008tDivisionPeer::NUM_COLUMNS - J008tDivisionPeer::NUM_LAZY_LOAD_COLUMNS);

		J007tRegionPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (J007tRegionPeer::NUM_COLUMNS - J007tRegionPeer::NUM_LAZY_LOAD_COLUMNS);

		J014tNegocioPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (J014tNegocioPeer::NUM_COLUMNS - J014tNegocioPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(J002tUsuarioPeer::CO_DIVISION,), array(J008tDivisionPeer::CO_DIVISION,), $join_behavior);
				$c->addJoin(array(J002tUsuarioPeer::CO_REGION,), array(J007tRegionPeer::CO_REGION,), $join_behavior);
				$c->addJoin(array(J002tUsuarioPeer::CO_NEGOCIO,), array(J014tNegocioPeer::CO_NEGOCIO,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = J002tUsuarioPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = J002tUsuarioPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = J002tUsuarioPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				J002tUsuarioPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined J008tDivision rows

				$key2 = J008tDivisionPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = J008tDivisionPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = J008tDivisionPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					J008tDivisionPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (J002tUsuario) to the collection in $obj2 (J008tDivision)
				$obj2->addJ002tUsuario($obj1);

			} // if joined row is not null

				// Add objects for joined J007tRegion rows

				$key3 = J007tRegionPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = J007tRegionPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = J007tRegionPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					J007tRegionPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (J002tUsuario) to the collection in $obj3 (J007tRegion)
				$obj3->addJ002tUsuario($obj1);

			} // if joined row is not null

				// Add objects for joined J014tNegocio rows

				$key4 = J014tNegocioPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = J014tNegocioPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = J014tNegocioPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					J014tNegocioPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (J002tUsuario) to the collection in $obj4 (J014tNegocio)
				$obj4->addJ002tUsuario($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of J002tUsuario objects pre-filled with all related objects except J007tRegion.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of J002tUsuario objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptJ007tRegion(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		J002tUsuarioPeer::addSelectColumns($c);
		$startcol2 = (J002tUsuarioPeer::NUM_COLUMNS - J002tUsuarioPeer::NUM_LAZY_LOAD_COLUMNS);

		J008tDivisionPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (J008tDivisionPeer::NUM_COLUMNS - J008tDivisionPeer::NUM_LAZY_LOAD_COLUMNS);

		J003tRolPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (J003tRolPeer::NUM_COLUMNS - J003tRolPeer::NUM_LAZY_LOAD_COLUMNS);

		J014tNegocioPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (J014tNegocioPeer::NUM_COLUMNS - J014tNegocioPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(J002tUsuarioPeer::CO_DIVISION,), array(J008tDivisionPeer::CO_DIVISION,), $join_behavior);
				$c->addJoin(array(J002tUsuarioPeer::CO_ROL,), array(J003tRolPeer::CO_ROL,), $join_behavior);
				$c->addJoin(array(J002tUsuarioPeer::CO_NEGOCIO,), array(J014tNegocioPeer::CO_NEGOCIO,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = J002tUsuarioPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = J002tUsuarioPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = J002tUsuarioPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				J002tUsuarioPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined J008tDivision rows

				$key2 = J008tDivisionPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = J008tDivisionPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = J008tDivisionPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					J008tDivisionPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (J002tUsuario) to the collection in $obj2 (J008tDivision)
				$obj2->addJ002tUsuario($obj1);

			} // if joined row is not null

				// Add objects for joined J003tRol rows

				$key3 = J003tRolPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = J003tRolPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = J003tRolPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					J003tRolPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (J002tUsuario) to the collection in $obj3 (J003tRol)
				$obj3->addJ002tUsuario($obj1);

			} // if joined row is not null

				// Add objects for joined J014tNegocio rows

				$key4 = J014tNegocioPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = J014tNegocioPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = J014tNegocioPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					J014tNegocioPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (J002tUsuario) to the collection in $obj4 (J014tNegocio)
				$obj4->addJ002tUsuario($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of J002tUsuario objects pre-filled with all related objects except J014tNegocio.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of J002tUsuario objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptJ014tNegocio(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		J002tUsuarioPeer::addSelectColumns($c);
		$startcol2 = (J002tUsuarioPeer::NUM_COLUMNS - J002tUsuarioPeer::NUM_LAZY_LOAD_COLUMNS);

		J008tDivisionPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (J008tDivisionPeer::NUM_COLUMNS - J008tDivisionPeer::NUM_LAZY_LOAD_COLUMNS);

		J003tRolPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (J003tRolPeer::NUM_COLUMNS - J003tRolPeer::NUM_LAZY_LOAD_COLUMNS);

		J007tRegionPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (J007tRegionPeer::NUM_COLUMNS - J007tRegionPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(J002tUsuarioPeer::CO_DIVISION,), array(J008tDivisionPeer::CO_DIVISION,), $join_behavior);
				$c->addJoin(array(J002tUsuarioPeer::CO_ROL,), array(J003tRolPeer::CO_ROL,), $join_behavior);
				$c->addJoin(array(J002tUsuarioPeer::CO_REGION,), array(J007tRegionPeer::CO_REGION,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = J002tUsuarioPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = J002tUsuarioPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = J002tUsuarioPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				J002tUsuarioPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined J008tDivision rows

				$key2 = J008tDivisionPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = J008tDivisionPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = J008tDivisionPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					J008tDivisionPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (J002tUsuario) to the collection in $obj2 (J008tDivision)
				$obj2->addJ002tUsuario($obj1);

			} // if joined row is not null

				// Add objects for joined J003tRol rows

				$key3 = J003tRolPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = J003tRolPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = J003tRolPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					J003tRolPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (J002tUsuario) to the collection in $obj3 (J003tRol)
				$obj3->addJ002tUsuario($obj1);

			} // if joined row is not null

				// Add objects for joined J007tRegion rows

				$key4 = J007tRegionPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = J007tRegionPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = J007tRegionPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					J007tRegionPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (J002tUsuario) to the collection in $obj4 (J007tRegion)
				$obj4->addJ002tUsuario($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


  static public function getUniqueColumnNames()
  {
    return array(array('tx_indicador'));
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return J002tUsuarioPeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a J002tUsuario or Criteria object.
	 *
	 * @param      mixed $values Criteria or J002tUsuario object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseJ002tUsuarioPeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseJ002tUsuarioPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(J002tUsuarioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from J002tUsuario object
		}

		if ($criteria->containsKey(J002tUsuarioPeer::CO_USUARIO) && $criteria->keyContainsValue(J002tUsuarioPeer::CO_USUARIO) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.J002tUsuarioPeer::CO_USUARIO.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseJ002tUsuarioPeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseJ002tUsuarioPeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a J002tUsuario or Criteria object.
	 *
	 * @param      mixed $values Criteria or J002tUsuario object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseJ002tUsuarioPeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseJ002tUsuarioPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(J002tUsuarioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(J002tUsuarioPeer::CO_USUARIO);
			$selectCriteria->add(J002tUsuarioPeer::CO_USUARIO, $criteria->remove(J002tUsuarioPeer::CO_USUARIO), $comparison);

		} else { // $values is J002tUsuario object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseJ002tUsuarioPeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseJ002tUsuarioPeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the j002t_usuario table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(J002tUsuarioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(J002tUsuarioPeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a J002tUsuario or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or J002tUsuario object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(J002tUsuarioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			J002tUsuarioPeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof J002tUsuario) {
			// invalidate the cache for this single object
			J002tUsuarioPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(J002tUsuarioPeer::CO_USUARIO, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				J002tUsuarioPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given J002tUsuario object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      J002tUsuario $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(J002tUsuario $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(J002tUsuarioPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(J002tUsuarioPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(J002tUsuarioPeer::DATABASE_NAME, J002tUsuarioPeer::TABLE_NAME, $columns);
    if ($res !== true) {
        $request = sfContext::getInstance()->getRequest();
        foreach ($res as $failed) {
            $col = J002tUsuarioPeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      string $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     J002tUsuario
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = J002tUsuarioPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(J002tUsuarioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(J002tUsuarioPeer::DATABASE_NAME);
		$criteria->add(J002tUsuarioPeer::CO_USUARIO, $pk);

		$v = J002tUsuarioPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(J002tUsuarioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(J002tUsuarioPeer::DATABASE_NAME);
			$criteria->add(J002tUsuarioPeer::CO_USUARIO, $pks, Criteria::IN);
			$objs = J002tUsuarioPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

} // BaseJ002tUsuarioPeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the J002tUsuarioPeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the J002tUsuarioPeer class:
//
// Propel::getDatabaseMap(J002tUsuarioPeer::DATABASE_NAME)->addTableBuilder(J002tUsuarioPeer::TABLE_NAME, J002tUsuarioPeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseJ002tUsuarioPeer::DATABASE_NAME)->addTableBuilder(BaseJ002tUsuarioPeer::TABLE_NAME, BaseJ002tUsuarioPeer::getMapBuilder());

