<?php
// auto-generated by sfGeneratorConfigHandler
// date: 2015/11/12 13:41:48
require sfConfig::get('sf_symfony_lib_dir').'/plugins/sfCompat10Plugin/config/config.php';
require_once(sfConfig::get('sf_module_cache_dir').'/autoJ001tMenu/actions/actions.class.php');

