<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/11/11 14:40:40

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'DebugPDO',
  'dsn' => 'pgsql:dbname=sti;host=162.122.74.96',
  'username' => 'postgres',
  'password' => 'postgres123',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
